/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxTerminalWritePost200Response
 */
export interface CoderouterApiSandboxTerminalWritePost200Response {
    /**
     * The output of the write command.
     * @type {string}
     * @memberof CoderouterApiSandboxTerminalWritePost200Response
     */
    output: string;
}

/**
 * Check if a given object implements the CoderouterApiSandboxTerminalWritePost200Response interface.
 */
export function instanceOfCoderouterApiSandboxTerminalWritePost200Response(
    value: object,
): value is CoderouterApiSandboxTerminalWritePost200Response {
    if (!('output' in value) || value['output'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxTerminalWritePost200ResponseFromJSON(
    json: any,
): CoderouterApiSandboxTerminalWritePost200Response {
    return CoderouterApiSandboxTerminalWritePost200ResponseFromJSONTyped(json, false);
}

export function CoderouterApiSandboxTerminalWritePost200ResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxTerminalWritePost200Response {
    if (json == null) {
        return json;
    }
    return {
        output: json['output'],
    };
}

export function CoderouterApiSandboxTerminalWritePost200ResponseToJSON(
    json: any,
): CoderouterApiSandboxTerminalWritePost200Response {
    return CoderouterApiSandboxTerminalWritePost200ResponseToJSONTyped(json, false);
}

export function CoderouterApiSandboxTerminalWritePost200ResponseToJSONTyped(
    value?: CoderouterApiSandboxTerminalWritePost200Response | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        output: value['output'],
    };
}
