/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxFileListPostRequest
 */
export interface CoderouterApiSandboxFileListPostRequest {
    /**
     * The path of the directory to list.
     * @type {string}
     * @memberof CoderouterApiSandboxFileListPostRequest
     */
    path: string;
}

/**
 * Check if a given object implements the CoderouterApiSandboxFileListPostRequest interface.
 */
export function instanceOfCoderouterApiSandboxFileListPostRequest(
    value: object,
): value is CoderouterApiSandboxFileListPostRequest {
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxFileListPostRequestFromJSON(
    json: any,
): CoderouterApiSandboxFileListPostRequest {
    return CoderouterApiSandboxFileListPostRequestFromJSONTyped(json, false);
}

export function CoderouterApiSandboxFileListPostRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxFileListPostRequest {
    if (json == null) {
        return json;
    }
    return {
        path: json['path'],
    };
}

export function CoderouterApiSandboxFileListPostRequestToJSON(
    json: any,
): CoderouterApiSandboxFileListPostRequest {
    return CoderouterApiSandboxFileListPostRequestToJSONTyped(json, false);
}

export function CoderouterApiSandboxFileListPostRequestToJSONTyped(
    value?: CoderouterApiSandboxFileListPostRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        path: value['path'],
    };
}
