/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxTerminalOpenPost200Response
 */
export interface CoderouterApiSandboxTerminalOpenPost200Response {
    /**
     * The output of the open command.
     * @type {string}
     * @memberof CoderouterApiSandboxTerminalOpenPost200Response
     */
    output: string;
}

/**
 * Check if a given object implements the CoderouterApiSandboxTerminalOpenPost200Response interface.
 */
export function instanceOfCoderouterApiSandboxTerminalOpenPost200Response(
    value: object,
): value is CoderouterApiSandboxTerminalOpenPost200Response {
    if (!('output' in value) || value['output'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxTerminalOpenPost200ResponseFromJSON(
    json: any,
): CoderouterApiSandboxTerminalOpenPost200Response {
    return CoderouterApiSandboxTerminalOpenPost200ResponseFromJSONTyped(json, false);
}

export function CoderouterApiSandboxTerminalOpenPost200ResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxTerminalOpenPost200Response {
    if (json == null) {
        return json;
    }
    return {
        output: json['output'],
    };
}

export function CoderouterApiSandboxTerminalOpenPost200ResponseToJSON(
    json: any,
): CoderouterApiSandboxTerminalOpenPost200Response {
    return CoderouterApiSandboxTerminalOpenPost200ResponseToJSONTyped(json, false);
}

export function CoderouterApiSandboxTerminalOpenPost200ResponseToJSONTyped(
    value?: CoderouterApiSandboxTerminalOpenPost200Response | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        output: value['output'],
    };
}
