/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxFileRenamePostRequest
 */
export interface CoderouterApiSandboxFileRenamePostRequest {
    /**
     * The path of the file to rename.
     * @type {string}
     * @memberof CoderouterApiSandboxFileRenamePostRequest
     */
    oldPath: string;
    /**
     * The new path of the file.
     * @type {string}
     * @memberof CoderouterApiSandboxFileRenamePostRequest
     */
    newPath: string;
}

/**
 * Check if a given object implements the CoderouterApiSandboxFileRenamePostRequest interface.
 */
export function instanceOfCoderouterApiSandboxFileRenamePostRequest(
    value: object,
): value is CoderouterApiSandboxFileRenamePostRequest {
    if (!('oldPath' in value) || value['oldPath'] === undefined) return false;
    if (!('newPath' in value) || value['newPath'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxFileRenamePostRequestFromJSON(
    json: any,
): CoderouterApiSandboxFileRenamePostRequest {
    return CoderouterApiSandboxFileRenamePostRequestFromJSONTyped(json, false);
}

export function CoderouterApiSandboxFileRenamePostRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxFileRenamePostRequest {
    if (json == null) {
        return json;
    }
    return {
        oldPath: json['oldPath'],
        newPath: json['newPath'],
    };
}

export function CoderouterApiSandboxFileRenamePostRequestToJSON(
    json: any,
): CoderouterApiSandboxFileRenamePostRequest {
    return CoderouterApiSandboxFileRenamePostRequestToJSONTyped(json, false);
}

export function CoderouterApiSandboxFileRenamePostRequestToJSONTyped(
    value?: CoderouterApiSandboxFileRenamePostRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        oldPath: value['oldPath'],
        newPath: value['newPath'],
    };
}
