/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxFileStatPost200Response
 */
export interface CoderouterApiSandboxFileStatPost200Response {
    /**
     *
     * @type {string}
     * @memberof CoderouterApiSandboxFileStatPost200Response
     */
    type: CoderouterApiSandboxFileStatPost200ResponseTypeEnum;
}

/**
 * @export
 */
export const CoderouterApiSandboxFileStatPost200ResponseTypeEnum = {
    File: 'file',
    Directory: 'directory',
} as const;
export type CoderouterApiSandboxFileStatPost200ResponseTypeEnum =
    (typeof CoderouterApiSandboxFileStatPost200ResponseTypeEnum)[keyof typeof CoderouterApiSandboxFileStatPost200ResponseTypeEnum];

/**
 * Check if a given object implements the CoderouterApiSandboxFileStatPost200Response interface.
 */
export function instanceOfCoderouterApiSandboxFileStatPost200Response(
    value: object,
): value is CoderouterApiSandboxFileStatPost200Response {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxFileStatPost200ResponseFromJSON(
    json: any,
): CoderouterApiSandboxFileStatPost200Response {
    return CoderouterApiSandboxFileStatPost200ResponseFromJSONTyped(json, false);
}

export function CoderouterApiSandboxFileStatPost200ResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxFileStatPost200Response {
    if (json == null) {
        return json;
    }
    return {
        type: json['type'],
    };
}

export function CoderouterApiSandboxFileStatPost200ResponseToJSON(
    json: any,
): CoderouterApiSandboxFileStatPost200Response {
    return CoderouterApiSandboxFileStatPost200ResponseToJSONTyped(json, false);
}

export function CoderouterApiSandboxFileStatPost200ResponseToJSONTyped(
    value?: CoderouterApiSandboxFileStatPost200Response | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        type: value['type'],
    };
}
