/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiAuthSignPost200Response
 */
export interface CoderouterApiAuthSignPost200Response {
    /**
     * The JWT token to send when interacting with the API as header "X-Auth-Jwt.".
     * @type {string}
     * @memberof CoderouterApiAuthSignPost200Response
     */
    jwt: string;
}

/**
 * Check if a given object implements the CoderouterApiAuthSignPost200Response interface.
 */
export function instanceOfCoderouterApiAuthSignPost200Response(
    value: object,
): value is CoderouterApiAuthSignPost200Response {
    if (!('jwt' in value) || value['jwt'] === undefined) return false;
    return true;
}

export function CoderouterApiAuthSignPost200ResponseFromJSON(
    json: any,
): CoderouterApiAuthSignPost200Response {
    return CoderouterApiAuthSignPost200ResponseFromJSONTyped(json, false);
}

export function CoderouterApiAuthSignPost200ResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiAuthSignPost200Response {
    if (json == null) {
        return json;
    }
    return {
        jwt: json['jwt'],
    };
}

export function CoderouterApiAuthSignPost200ResponseToJSON(
    json: any,
): CoderouterApiAuthSignPost200Response {
    return CoderouterApiAuthSignPost200ResponseToJSONTyped(json, false);
}

export function CoderouterApiAuthSignPost200ResponseToJSONTyped(
    value?: CoderouterApiAuthSignPost200Response | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        jwt: value['jwt'],
    };
}
