/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiAuthSignPost401Response
 */
export interface CoderouterApiAuthSignPost401Response {
    /**
     *
     * @type {string}
     * @memberof CoderouterApiAuthSignPost401Response
     */
    error: string;
}

/**
 * Check if a given object implements the CoderouterApiAuthSignPost401Response interface.
 */
export function instanceOfCoderouterApiAuthSignPost401Response(
    value: object,
): value is CoderouterApiAuthSignPost401Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function CoderouterApiAuthSignPost401ResponseFromJSON(
    json: any,
): CoderouterApiAuthSignPost401Response {
    return CoderouterApiAuthSignPost401ResponseFromJSONTyped(json, false);
}

export function CoderouterApiAuthSignPost401ResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiAuthSignPost401Response {
    if (json == null) {
        return json;
    }
    return {
        error: json['error'],
    };
}

export function CoderouterApiAuthSignPost401ResponseToJSON(
    json: any,
): CoderouterApiAuthSignPost401Response {
    return CoderouterApiAuthSignPost401ResponseToJSONTyped(json, false);
}

export function CoderouterApiAuthSignPost401ResponseToJSONTyped(
    value?: CoderouterApiAuthSignPost401Response | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        error: value['error'],
    };
}
