/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxFileCopyPostRequest
 */
export interface CoderouterApiSandboxFileCopyPostRequest {
    /**
     * The path of the source file.
     * @type {string}
     * @memberof CoderouterApiSandboxFileCopyPostRequest
     */
    source: string;
    /**
     * The path of the destination file.
     * @type {string}
     * @memberof CoderouterApiSandboxFileCopyPostRequest
     */
    destination: string;
    /**
     * Whether to overwrite the destination file if it already exists.
     * @type {boolean}
     * @memberof CoderouterApiSandboxFileCopyPostRequest
     */
    overwrite: boolean;
    /**
     * Whether to copy the file recursively.
     * @type {boolean}
     * @memberof CoderouterApiSandboxFileCopyPostRequest
     */
    recursive: boolean;
}

/**
 * Check if a given object implements the CoderouterApiSandboxFileCopyPostRequest interface.
 */
export function instanceOfCoderouterApiSandboxFileCopyPostRequest(
    value: object,
): value is CoderouterApiSandboxFileCopyPostRequest {
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('destination' in value) || value['destination'] === undefined) return false;
    if (!('overwrite' in value) || value['overwrite'] === undefined) return false;
    if (!('recursive' in value) || value['recursive'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxFileCopyPostRequestFromJSON(
    json: any,
): CoderouterApiSandboxFileCopyPostRequest {
    return CoderouterApiSandboxFileCopyPostRequestFromJSONTyped(json, false);
}

export function CoderouterApiSandboxFileCopyPostRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxFileCopyPostRequest {
    if (json == null) {
        return json;
    }
    return {
        source: json['source'],
        destination: json['destination'],
        overwrite: json['overwrite'],
        recursive: json['recursive'],
    };
}

export function CoderouterApiSandboxFileCopyPostRequestToJSON(
    json: any,
): CoderouterApiSandboxFileCopyPostRequest {
    return CoderouterApiSandboxFileCopyPostRequestToJSONTyped(json, false);
}

export function CoderouterApiSandboxFileCopyPostRequestToJSONTyped(
    value?: CoderouterApiSandboxFileCopyPostRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        source: value['source'],
        destination: value['destination'],
        overwrite: value['overwrite'],
        recursive: value['recursive'],
    };
}
