/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxTerminalRunPost200Response
 */
export interface CoderouterApiSandboxTerminalRunPost200Response {
    /**
     * The output of the run command. The output includes lines before and after the command execution.
     * @type {string}
     * @memberof CoderouterApiSandboxTerminalRunPost200Response
     */
    output: string;
}

/**
 * Check if a given object implements the CoderouterApiSandboxTerminalRunPost200Response interface.
 */
export function instanceOfCoderouterApiSandboxTerminalRunPost200Response(
    value: object,
): value is CoderouterApiSandboxTerminalRunPost200Response {
    if (!('output' in value) || value['output'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxTerminalRunPost200ResponseFromJSON(
    json: any,
): CoderouterApiSandboxTerminalRunPost200Response {
    return CoderouterApiSandboxTerminalRunPost200ResponseFromJSONTyped(json, false);
}

export function CoderouterApiSandboxTerminalRunPost200ResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxTerminalRunPost200Response {
    if (json == null) {
        return json;
    }
    return {
        output: json['output'],
    };
}

export function CoderouterApiSandboxTerminalRunPost200ResponseToJSON(
    json: any,
): CoderouterApiSandboxTerminalRunPost200Response {
    return CoderouterApiSandboxTerminalRunPost200ResponseToJSONTyped(json, false);
}

export function CoderouterApiSandboxTerminalRunPost200ResponseToJSONTyped(
    value?: CoderouterApiSandboxTerminalRunPost200Response | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        output: value['output'],
    };
}
