/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxTerminalKillPostRequest
 */
export interface CoderouterApiSandboxTerminalKillPostRequest {
    /**
     * The ID of the terminal.
     * @type {string}
     * @memberof CoderouterApiSandboxTerminalKillPostRequest
     */
    terminalId: string;
}

/**
 * Check if a given object implements the CoderouterApiSandboxTerminalKillPostRequest interface.
 */
export function instanceOfCoderouterApiSandboxTerminalKillPostRequest(
    value: object,
): value is CoderouterApiSandboxTerminalKillPostRequest {
    if (!('terminalId' in value) || value['terminalId'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxTerminalKillPostRequestFromJSON(
    json: any,
): CoderouterApiSandboxTerminalKillPostRequest {
    return CoderouterApiSandboxTerminalKillPostRequestFromJSONTyped(json, false);
}

export function CoderouterApiSandboxTerminalKillPostRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxTerminalKillPostRequest {
    if (json == null) {
        return json;
    }
    return {
        terminalId: json['terminalId'],
    };
}

export function CoderouterApiSandboxTerminalKillPostRequestToJSON(
    json: any,
): CoderouterApiSandboxTerminalKillPostRequest {
    return CoderouterApiSandboxTerminalKillPostRequestToJSONTyped(json, false);
}

export function CoderouterApiSandboxTerminalKillPostRequestToJSONTyped(
    value?: CoderouterApiSandboxTerminalKillPostRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        terminalId: value['terminalId'],
    };
}
