/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxTerminalCreatePostRequest
 */
export interface CoderouterApiSandboxTerminalCreatePostRequest {
    /**
     * The ID of the terminal.
     * @type {string}
     * @memberof CoderouterApiSandboxTerminalCreatePostRequest
     */
    terminalId: string;
    /**
     * The name of the terminal.
     * @type {string}
     * @memberof CoderouterApiSandboxTerminalCreatePostRequest
     */
    name: string;
}

/**
 * Check if a given object implements the CoderouterApiSandboxTerminalCreatePostRequest interface.
 */
export function instanceOfCoderouterApiSandboxTerminalCreatePostRequest(
    value: object,
): value is CoderouterApiSandboxTerminalCreatePostRequest {
    if (!('terminalId' in value) || value['terminalId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxTerminalCreatePostRequestFromJSON(
    json: any,
): CoderouterApiSandboxTerminalCreatePostRequest {
    return CoderouterApiSandboxTerminalCreatePostRequestFromJSONTyped(json, false);
}

export function CoderouterApiSandboxTerminalCreatePostRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxTerminalCreatePostRequest {
    if (json == null) {
        return json;
    }
    return {
        terminalId: json['terminalId'],
        name: json['name'],
    };
}

export function CoderouterApiSandboxTerminalCreatePostRequestToJSON(
    json: any,
): CoderouterApiSandboxTerminalCreatePostRequest {
    return CoderouterApiSandboxTerminalCreatePostRequestToJSONTyped(json, false);
}

export function CoderouterApiSandboxTerminalCreatePostRequestToJSONTyped(
    value?: CoderouterApiSandboxTerminalCreatePostRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        terminalId: value['terminalId'],
        name: value['name'],
    };
}
