/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxFileReadPost200Response
 */
export interface CoderouterApiSandboxFileReadPost200Response {
    /**
     *
     * @type {string}
     * @memberof CoderouterApiSandboxFileReadPost200Response
     */
    data: string;
}

/**
 * Check if a given object implements the CoderouterApiSandboxFileReadPost200Response interface.
 */
export function instanceOfCoderouterApiSandboxFileReadPost200Response(
    value: object,
): value is CoderouterApiSandboxFileReadPost200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxFileReadPost200ResponseFromJSON(
    json: any,
): CoderouterApiSandboxFileReadPost200Response {
    return CoderouterApiSandboxFileReadPost200ResponseFromJSONTyped(json, false);
}

export function CoderouterApiSandboxFileReadPost200ResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxFileReadPost200Response {
    if (json == null) {
        return json;
    }
    return {
        data: json['data'],
    };
}

export function CoderouterApiSandboxFileReadPost200ResponseToJSON(
    json: any,
): CoderouterApiSandboxFileReadPost200Response {
    return CoderouterApiSandboxFileReadPost200ResponseToJSONTyped(json, false);
}

export function CoderouterApiSandboxFileReadPost200ResponseToJSONTyped(
    value?: CoderouterApiSandboxFileReadPost200Response | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        data: value['data'],
    };
}
