/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxFileWritePostRequestFilesInner
 */
export interface CoderouterApiSandboxFileWritePostRequestFilesInner {
    /**
     * The path of the file to write.
     * @type {string}
     * @memberof CoderouterApiSandboxFileWritePostRequestFilesInner
     */
    path: string;
    /**
     * The content of the file to write.
     * @type {string}
     * @memberof CoderouterApiSandboxFileWritePostRequestFilesInner
     */
    data: string;
    /**
     * Whether to overwrite the file if it already exists.
     * @type {boolean}
     * @memberof CoderouterApiSandboxFileWritePostRequestFilesInner
     */
    overwrite: boolean;
}

/**
 * Check if a given object implements the CoderouterApiSandboxFileWritePostRequestFilesInner interface.
 */
export function instanceOfCoderouterApiSandboxFileWritePostRequestFilesInner(
    value: object,
): value is CoderouterApiSandboxFileWritePostRequestFilesInner {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('overwrite' in value) || value['overwrite'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxFileWritePostRequestFilesInnerFromJSON(
    json: any,
): CoderouterApiSandboxFileWritePostRequestFilesInner {
    return CoderouterApiSandboxFileWritePostRequestFilesInnerFromJSONTyped(json, false);
}

export function CoderouterApiSandboxFileWritePostRequestFilesInnerFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxFileWritePostRequestFilesInner {
    if (json == null) {
        return json;
    }
    return {
        path: json['path'],
        data: json['data'],
        overwrite: json['overwrite'],
    };
}

export function CoderouterApiSandboxFileWritePostRequestFilesInnerToJSON(
    json: any,
): CoderouterApiSandboxFileWritePostRequestFilesInner {
    return CoderouterApiSandboxFileWritePostRequestFilesInnerToJSONTyped(json, false);
}

export function CoderouterApiSandboxFileWritePostRequestFilesInnerToJSONTyped(
    value?: CoderouterApiSandboxFileWritePostRequestFilesInner | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        path: value['path'],
        data: value['data'],
        overwrite: value['overwrite'],
    };
}
