/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiAuthSignPostRequest
 */
export interface CoderouterApiAuthSignPostRequest {
    /**
     * The ID of the sandbox. This is your own ID. It can be a UUID or any unique string. Required when using a sandbox.
     * @type {string}
     * @memberof CoderouterApiAuthSignPostRequest
     */
    sandboxId?: string;
    /**
     * The ID of the user. This is your own ID. It can be a UUID or any unique string.
     * @type {string}
     * @memberof CoderouterApiAuthSignPostRequest
     */
    userId?: string;
}

/**
 * Check if a given object implements the CoderouterApiAuthSignPostRequest interface.
 */
export function instanceOfCoderouterApiAuthSignPostRequest(
    value: object,
): value is CoderouterApiAuthSignPostRequest {
    return true;
}

export function CoderouterApiAuthSignPostRequestFromJSON(
    json: any,
): CoderouterApiAuthSignPostRequest {
    return CoderouterApiAuthSignPostRequestFromJSONTyped(json, false);
}

export function CoderouterApiAuthSignPostRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiAuthSignPostRequest {
    if (json == null) {
        return json;
    }
    return {
        sandboxId: json['sandboxId'] == null ? undefined : json['sandboxId'],
        userId: json['userId'] == null ? undefined : json['userId'],
    };
}

export function CoderouterApiAuthSignPostRequestToJSON(
    json: any,
): CoderouterApiAuthSignPostRequest {
    return CoderouterApiAuthSignPostRequestToJSONTyped(json, false);
}

export function CoderouterApiAuthSignPostRequestToJSONTyped(
    value?: CoderouterApiAuthSignPostRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        sandboxId: value['sandboxId'],
        userId: value['userId'],
    };
}
