/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoderouterApiSandboxFileWritePostRequestFilesInner } from './CoderouterApiSandboxFileWritePostRequestFilesInner';
import {
    CoderouterApiSandboxFileWritePostRequestFilesInnerFromJSON,
    CoderouterApiSandboxFileWritePostRequestFilesInnerFromJSONTyped,
    CoderouterApiSandboxFileWritePostRequestFilesInnerToJSON,
    CoderouterApiSandboxFileWritePostRequestFilesInnerToJSONTyped,
} from './CoderouterApiSandboxFileWritePostRequestFilesInner';

/**
 *
 * @export
 * @interface CoderouterApiSandboxFileWritePostRequest
 */
export interface CoderouterApiSandboxFileWritePostRequest {
    /**
     *
     * @type {Array<CoderouterApiSandboxFileWritePostRequestFilesInner>}
     * @memberof CoderouterApiSandboxFileWritePostRequest
     */
    files: Array<CoderouterApiSandboxFileWritePostRequestFilesInner>;
}

/**
 * Check if a given object implements the CoderouterApiSandboxFileWritePostRequest interface.
 */
export function instanceOfCoderouterApiSandboxFileWritePostRequest(
    value: object,
): value is CoderouterApiSandboxFileWritePostRequest {
    if (!('files' in value) || value['files'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxFileWritePostRequestFromJSON(
    json: any,
): CoderouterApiSandboxFileWritePostRequest {
    return CoderouterApiSandboxFileWritePostRequestFromJSONTyped(json, false);
}

export function CoderouterApiSandboxFileWritePostRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxFileWritePostRequest {
    if (json == null) {
        return json;
    }
    return {
        files: (json['files'] as Array<any>).map(
            CoderouterApiSandboxFileWritePostRequestFilesInnerFromJSON,
        ),
    };
}

export function CoderouterApiSandboxFileWritePostRequestToJSON(
    json: any,
): CoderouterApiSandboxFileWritePostRequest {
    return CoderouterApiSandboxFileWritePostRequestToJSONTyped(json, false);
}

export function CoderouterApiSandboxFileWritePostRequestToJSONTyped(
    value?: CoderouterApiSandboxFileWritePostRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        files: (value['files'] as Array<any>).map(
            CoderouterApiSandboxFileWritePostRequestFilesInnerToJSON,
        ),
    };
}
