/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxFileReadPostRequest
 */
export interface CoderouterApiSandboxFileReadPostRequest {
    /**
     * The path of the file to read.
     * @type {string}
     * @memberof CoderouterApiSandboxFileReadPostRequest
     */
    path: string;
}

/**
 * Check if a given object implements the CoderouterApiSandboxFileReadPostRequest interface.
 */
export function instanceOfCoderouterApiSandboxFileReadPostRequest(
    value: object,
): value is CoderouterApiSandboxFileReadPostRequest {
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxFileReadPostRequestFromJSON(
    json: any,
): CoderouterApiSandboxFileReadPostRequest {
    return CoderouterApiSandboxFileReadPostRequestFromJSONTyped(json, false);
}

export function CoderouterApiSandboxFileReadPostRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxFileReadPostRequest {
    if (json == null) {
        return json;
    }
    return {
        path: json['path'],
    };
}

export function CoderouterApiSandboxFileReadPostRequestToJSON(
    json: any,
): CoderouterApiSandboxFileReadPostRequest {
    return CoderouterApiSandboxFileReadPostRequestToJSONTyped(json, false);
}

export function CoderouterApiSandboxFileReadPostRequestToJSONTyped(
    value?: CoderouterApiSandboxFileReadPostRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        path: value['path'],
    };
}
