/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoderouterApiSandboxFileWatchPost200ResponseEventsInner } from './CoderouterApiSandboxFileWatchPost200ResponseEventsInner';
import {
    CoderouterApiSandboxFileWatchPost200ResponseEventsInnerFromJSON,
    CoderouterApiSandboxFileWatchPost200ResponseEventsInnerFromJSONTyped,
    CoderouterApiSandboxFileWatchPost200ResponseEventsInnerToJSON,
    CoderouterApiSandboxFileWatchPost200ResponseEventsInnerToJSONTyped,
} from './CoderouterApiSandboxFileWatchPost200ResponseEventsInner';

/**
 *
 * @export
 * @interface CoderouterApiSandboxFileWatchPost200Response
 */
export interface CoderouterApiSandboxFileWatchPost200Response {
    /**
     *
     * @type {Array<CoderouterApiSandboxFileWatchPost200ResponseEventsInner>}
     * @memberof CoderouterApiSandboxFileWatchPost200Response
     */
    events: Array<CoderouterApiSandboxFileWatchPost200ResponseEventsInner>;
}

/**
 * Check if a given object implements the CoderouterApiSandboxFileWatchPost200Response interface.
 */
export function instanceOfCoderouterApiSandboxFileWatchPost200Response(
    value: object,
): value is CoderouterApiSandboxFileWatchPost200Response {
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxFileWatchPost200ResponseFromJSON(
    json: any,
): CoderouterApiSandboxFileWatchPost200Response {
    return CoderouterApiSandboxFileWatchPost200ResponseFromJSONTyped(json, false);
}

export function CoderouterApiSandboxFileWatchPost200ResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxFileWatchPost200Response {
    if (json == null) {
        return json;
    }
    return {
        events: (json['events'] as Array<any>).map(
            CoderouterApiSandboxFileWatchPost200ResponseEventsInnerFromJSON,
        ),
    };
}

export function CoderouterApiSandboxFileWatchPost200ResponseToJSON(
    json: any,
): CoderouterApiSandboxFileWatchPost200Response {
    return CoderouterApiSandboxFileWatchPost200ResponseToJSONTyped(json, false);
}

export function CoderouterApiSandboxFileWatchPost200ResponseToJSONTyped(
    value?: CoderouterApiSandboxFileWatchPost200Response | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        events: (value['events'] as Array<any>).map(
            CoderouterApiSandboxFileWatchPost200ResponseEventsInnerToJSON,
        ),
    };
}
