/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxUrlPost200Response
 */
export interface CoderouterApiSandboxUrlPost200Response {
    /**
     * The URL of the sandbox.
     * @type {string}
     * @memberof CoderouterApiSandboxUrlPost200Response
     */
    url: string;
}

/**
 * Check if a given object implements the CoderouterApiSandboxUrlPost200Response interface.
 */
export function instanceOfCoderouterApiSandboxUrlPost200Response(
    value: object,
): value is CoderouterApiSandboxUrlPost200Response {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxUrlPost200ResponseFromJSON(
    json: any,
): CoderouterApiSandboxUrlPost200Response {
    return CoderouterApiSandboxUrlPost200ResponseFromJSONTyped(json, false);
}

export function CoderouterApiSandboxUrlPost200ResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxUrlPost200Response {
    if (json == null) {
        return json;
    }
    return {
        url: json['url'],
    };
}

export function CoderouterApiSandboxUrlPost200ResponseToJSON(
    json: any,
): CoderouterApiSandboxUrlPost200Response {
    return CoderouterApiSandboxUrlPost200ResponseToJSONTyped(json, false);
}

export function CoderouterApiSandboxUrlPost200ResponseToJSONTyped(
    value?: CoderouterApiSandboxUrlPost200Response | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        url: value['url'],
    };
}
