/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxFileDeletePostRequest
 */
export interface CoderouterApiSandboxFileDeletePostRequest {
    /**
     * The path of the file to delete.
     * @type {string}
     * @memberof CoderouterApiSandboxFileDeletePostRequest
     */
    path: string;
}

/**
 * Check if a given object implements the CoderouterApiSandboxFileDeletePostRequest interface.
 */
export function instanceOfCoderouterApiSandboxFileDeletePostRequest(
    value: object,
): value is CoderouterApiSandboxFileDeletePostRequest {
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxFileDeletePostRequestFromJSON(
    json: any,
): CoderouterApiSandboxFileDeletePostRequest {
    return CoderouterApiSandboxFileDeletePostRequestFromJSONTyped(json, false);
}

export function CoderouterApiSandboxFileDeletePostRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxFileDeletePostRequest {
    if (json == null) {
        return json;
    }
    return {
        path: json['path'],
    };
}

export function CoderouterApiSandboxFileDeletePostRequestToJSON(
    json: any,
): CoderouterApiSandboxFileDeletePostRequest {
    return CoderouterApiSandboxFileDeletePostRequestToJSONTyped(json, false);
}

export function CoderouterApiSandboxFileDeletePostRequestToJSONTyped(
    value?: CoderouterApiSandboxFileDeletePostRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        path: value['path'],
    };
}
