/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxFileStatPostRequest
 */
export interface CoderouterApiSandboxFileStatPostRequest {
    /**
     * The path of the file to stat.
     * @type {string}
     * @memberof CoderouterApiSandboxFileStatPostRequest
     */
    path: string;
}

/**
 * Check if a given object implements the CoderouterApiSandboxFileStatPostRequest interface.
 */
export function instanceOfCoderouterApiSandboxFileStatPostRequest(
    value: object,
): value is CoderouterApiSandboxFileStatPostRequest {
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxFileStatPostRequestFromJSON(
    json: any,
): CoderouterApiSandboxFileStatPostRequest {
    return CoderouterApiSandboxFileStatPostRequestFromJSONTyped(json, false);
}

export function CoderouterApiSandboxFileStatPostRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxFileStatPostRequest {
    if (json == null) {
        return json;
    }
    return {
        path: json['path'],
    };
}

export function CoderouterApiSandboxFileStatPostRequestToJSON(
    json: any,
): CoderouterApiSandboxFileStatPostRequest {
    return CoderouterApiSandboxFileStatPostRequestToJSONTyped(json, false);
}

export function CoderouterApiSandboxFileStatPostRequestToJSONTyped(
    value?: CoderouterApiSandboxFileStatPostRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        path: value['path'],
    };
}
