/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxFileDownloadPostRequest
 */
export interface CoderouterApiSandboxFileDownloadPostRequest {
    /**
     * The path of the file to download.
     * @type {string}
     * @memberof CoderouterApiSandboxFileDownloadPostRequest
     */
    path: string;
}

/**
 * Check if a given object implements the CoderouterApiSandboxFileDownloadPostRequest interface.
 */
export function instanceOfCoderouterApiSandboxFileDownloadPostRequest(
    value: object,
): value is CoderouterApiSandboxFileDownloadPostRequest {
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxFileDownloadPostRequestFromJSON(
    json: any,
): CoderouterApiSandboxFileDownloadPostRequest {
    return CoderouterApiSandboxFileDownloadPostRequestFromJSONTyped(json, false);
}

export function CoderouterApiSandboxFileDownloadPostRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxFileDownloadPostRequest {
    if (json == null) {
        return json;
    }
    return {
        path: json['path'],
    };
}

export function CoderouterApiSandboxFileDownloadPostRequestToJSON(
    json: any,
): CoderouterApiSandboxFileDownloadPostRequest {
    return CoderouterApiSandboxFileDownloadPostRequestToJSONTyped(json, false);
}

export function CoderouterApiSandboxFileDownloadPostRequestToJSONTyped(
    value?: CoderouterApiSandboxFileDownloadPostRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        path: value['path'],
    };
}
