/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxCreatePost200Response
 */
export interface CoderouterApiSandboxCreatePost200Response {
    /**
     * The ID of the sandbox. This is your own ID. It can be a UUID or any unique string.
     * @type {string}
     * @memberof CoderouterApiSandboxCreatePost200Response
     */
    id: string;
}

/**
 * Check if a given object implements the CoderouterApiSandboxCreatePost200Response interface.
 */
export function instanceOfCoderouterApiSandboxCreatePost200Response(
    value: object,
): value is CoderouterApiSandboxCreatePost200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxCreatePost200ResponseFromJSON(
    json: any,
): CoderouterApiSandboxCreatePost200Response {
    return CoderouterApiSandboxCreatePost200ResponseFromJSONTyped(json, false);
}

export function CoderouterApiSandboxCreatePost200ResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxCreatePost200Response {
    if (json == null) {
        return json;
    }
    return {
        id: json['id'],
    };
}

export function CoderouterApiSandboxCreatePost200ResponseToJSON(
    json: any,
): CoderouterApiSandboxCreatePost200Response {
    return CoderouterApiSandboxCreatePost200ResponseToJSONTyped(json, false);
}

export function CoderouterApiSandboxCreatePost200ResponseToJSONTyped(
    value?: CoderouterApiSandboxCreatePost200Response | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value['id'],
    };
}
