/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxTerminalKillPost200Response
 */
export interface CoderouterApiSandboxTerminalKillPost200Response {
    /**
     * The output of the kill command.
     * @type {string}
     * @memberof CoderouterApiSandboxTerminalKillPost200Response
     */
    output: string;
}

/**
 * Check if a given object implements the CoderouterApiSandboxTerminalKillPost200Response interface.
 */
export function instanceOfCoderouterApiSandboxTerminalKillPost200Response(
    value: object,
): value is CoderouterApiSandboxTerminalKillPost200Response {
    if (!('output' in value) || value['output'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxTerminalKillPost200ResponseFromJSON(
    json: any,
): CoderouterApiSandboxTerminalKillPost200Response {
    return CoderouterApiSandboxTerminalKillPost200ResponseFromJSONTyped(json, false);
}

export function CoderouterApiSandboxTerminalKillPost200ResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxTerminalKillPost200Response {
    if (json == null) {
        return json;
    }
    return {
        output: json['output'],
    };
}

export function CoderouterApiSandboxTerminalKillPost200ResponseToJSON(
    json: any,
): CoderouterApiSandboxTerminalKillPost200Response {
    return CoderouterApiSandboxTerminalKillPost200ResponseToJSONTyped(json, false);
}

export function CoderouterApiSandboxTerminalKillPost200ResponseToJSONTyped(
    value?: CoderouterApiSandboxTerminalKillPost200Response | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        output: value['output'],
    };
}
