/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoderouterApiSandboxFileListPost200ResponseFilesInner } from './CoderouterApiSandboxFileListPost200ResponseFilesInner';
import {
    CoderouterApiSandboxFileListPost200ResponseFilesInnerFromJSON,
    CoderouterApiSandboxFileListPost200ResponseFilesInnerFromJSONTyped,
    CoderouterApiSandboxFileListPost200ResponseFilesInnerToJSON,
    CoderouterApiSandboxFileListPost200ResponseFilesInnerToJSONTyped,
} from './CoderouterApiSandboxFileListPost200ResponseFilesInner';

/**
 *
 * @export
 * @interface CoderouterApiSandboxFileListPost200Response
 */
export interface CoderouterApiSandboxFileListPost200Response {
    /**
     *
     * @type {Array<CoderouterApiSandboxFileListPost200ResponseFilesInner>}
     * @memberof CoderouterApiSandboxFileListPost200Response
     */
    files: Array<CoderouterApiSandboxFileListPost200ResponseFilesInner>;
}

/**
 * Check if a given object implements the CoderouterApiSandboxFileListPost200Response interface.
 */
export function instanceOfCoderouterApiSandboxFileListPost200Response(
    value: object,
): value is CoderouterApiSandboxFileListPost200Response {
    if (!('files' in value) || value['files'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxFileListPost200ResponseFromJSON(
    json: any,
): CoderouterApiSandboxFileListPost200Response {
    return CoderouterApiSandboxFileListPost200ResponseFromJSONTyped(json, false);
}

export function CoderouterApiSandboxFileListPost200ResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxFileListPost200Response {
    if (json == null) {
        return json;
    }
    return {
        files: (json['files'] as Array<any>).map(
            CoderouterApiSandboxFileListPost200ResponseFilesInnerFromJSON,
        ),
    };
}

export function CoderouterApiSandboxFileListPost200ResponseToJSON(
    json: any,
): CoderouterApiSandboxFileListPost200Response {
    return CoderouterApiSandboxFileListPost200ResponseToJSONTyped(json, false);
}

export function CoderouterApiSandboxFileListPost200ResponseToJSONTyped(
    value?: CoderouterApiSandboxFileListPost200Response | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        files: (value['files'] as Array<any>).map(
            CoderouterApiSandboxFileListPost200ResponseFilesInnerToJSON,
        ),
    };
}
