/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxFileWatchPostRequest
 */
export interface CoderouterApiSandboxFileWatchPostRequest {
    /**
     * The path of the file to write.
     * @type {string}
     * @memberof CoderouterApiSandboxFileWatchPostRequest
     */
    path: string;
    /**
     * Whether to watch the file recursively.
     * @type {boolean}
     * @memberof CoderouterApiSandboxFileWatchPostRequest
     */
    recursive: boolean;
    /**
     * The paths to exclude from the watch.
     * @type {Array<string>}
     * @memberof CoderouterApiSandboxFileWatchPostRequest
     */
    excludePaths: Array<string>;
}

/**
 * Check if a given object implements the CoderouterApiSandboxFileWatchPostRequest interface.
 */
export function instanceOfCoderouterApiSandboxFileWatchPostRequest(
    value: object,
): value is CoderouterApiSandboxFileWatchPostRequest {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('recursive' in value) || value['recursive'] === undefined) return false;
    if (!('excludePaths' in value) || value['excludePaths'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxFileWatchPostRequestFromJSON(
    json: any,
): CoderouterApiSandboxFileWatchPostRequest {
    return CoderouterApiSandboxFileWatchPostRequestFromJSONTyped(json, false);
}

export function CoderouterApiSandboxFileWatchPostRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxFileWatchPostRequest {
    if (json == null) {
        return json;
    }
    return {
        path: json['path'],
        recursive: json['recursive'],
        excludePaths: json['excludePaths'],
    };
}

export function CoderouterApiSandboxFileWatchPostRequestToJSON(
    json: any,
): CoderouterApiSandboxFileWatchPostRequest {
    return CoderouterApiSandboxFileWatchPostRequestToJSONTyped(json, false);
}

export function CoderouterApiSandboxFileWatchPostRequestToJSONTyped(
    value?: CoderouterApiSandboxFileWatchPostRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        path: value['path'],
        recursive: value['recursive'],
        excludePaths: value['excludePaths'],
    };
}
