/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxTerminalCommandPost200Response
 */
export interface CoderouterApiSandboxTerminalCommandPost200Response {
    /**
     * Whether the command was successful.
     * @type {boolean}
     * @memberof CoderouterApiSandboxTerminalCommandPost200Response
     */
    isError: boolean;
    /**
     * The output of the command.
     * @type {string}
     * @memberof CoderouterApiSandboxTerminalCommandPost200Response
     */
    output: string;
    /**
     * The stdout of the command.
     * @type {string}
     * @memberof CoderouterApiSandboxTerminalCommandPost200Response
     */
    stdout: string;
    /**
     * The stderr of the command.
     * @type {string}
     * @memberof CoderouterApiSandboxTerminalCommandPost200Response
     */
    stderr: string;
    /**
     * The exit code of the command.
     * @type {number}
     * @memberof CoderouterApiSandboxTerminalCommandPost200Response
     */
    exitCode: number;
}

/**
 * Check if a given object implements the CoderouterApiSandboxTerminalCommandPost200Response interface.
 */
export function instanceOfCoderouterApiSandboxTerminalCommandPost200Response(
    value: object,
): value is CoderouterApiSandboxTerminalCommandPost200Response {
    if (!('isError' in value) || value['isError'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('stdout' in value) || value['stdout'] === undefined) return false;
    if (!('stderr' in value) || value['stderr'] === undefined) return false;
    if (!('exitCode' in value) || value['exitCode'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxTerminalCommandPost200ResponseFromJSON(
    json: any,
): CoderouterApiSandboxTerminalCommandPost200Response {
    return CoderouterApiSandboxTerminalCommandPost200ResponseFromJSONTyped(json, false);
}

export function CoderouterApiSandboxTerminalCommandPost200ResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxTerminalCommandPost200Response {
    if (json == null) {
        return json;
    }
    return {
        isError: json['is_error'],
        output: json['output'],
        stdout: json['stdout'],
        stderr: json['stderr'],
        exitCode: json['exit_code'],
    };
}

export function CoderouterApiSandboxTerminalCommandPost200ResponseToJSON(
    json: any,
): CoderouterApiSandboxTerminalCommandPost200Response {
    return CoderouterApiSandboxTerminalCommandPost200ResponseToJSONTyped(json, false);
}

export function CoderouterApiSandboxTerminalCommandPost200ResponseToJSONTyped(
    value?: CoderouterApiSandboxTerminalCommandPost200Response | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        is_error: value['isError'],
        output: value['output'],
        stdout: value['stdout'],
        stderr: value['stderr'],
        exit_code: value['exitCode'],
    };
}
