/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxCreatePostRequest
 */
export interface CoderouterApiSandboxCreatePostRequest {
    /**
     * The ID of the template to use for the sandbox.
     * @type {string}
     * @memberof CoderouterApiSandboxCreatePostRequest
     */
    templateId: string;
    /**
     * The metadata of the sandbox.
     * @type {{ [key: string]: string; }}
     * @memberof CoderouterApiSandboxCreatePostRequest
     */
    metadata: { [key: string]: string };
}

/**
 * Check if a given object implements the CoderouterApiSandboxCreatePostRequest interface.
 */
export function instanceOfCoderouterApiSandboxCreatePostRequest(
    value: object,
): value is CoderouterApiSandboxCreatePostRequest {
    if (!('templateId' in value) || value['templateId'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxCreatePostRequestFromJSON(
    json: any,
): CoderouterApiSandboxCreatePostRequest {
    return CoderouterApiSandboxCreatePostRequestFromJSONTyped(json, false);
}

export function CoderouterApiSandboxCreatePostRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxCreatePostRequest {
    if (json == null) {
        return json;
    }
    return {
        templateId: json['templateId'],
        metadata: json['metadata'],
    };
}

export function CoderouterApiSandboxCreatePostRequestToJSON(
    json: any,
): CoderouterApiSandboxCreatePostRequest {
    return CoderouterApiSandboxCreatePostRequestToJSONTyped(json, false);
}

export function CoderouterApiSandboxCreatePostRequestToJSONTyped(
    value?: CoderouterApiSandboxCreatePostRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        templateId: value['templateId'],
        metadata: value['metadata'],
    };
}
