/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxFileWatchPost200ResponseEventsInner
 */
export interface CoderouterApiSandboxFileWatchPost200ResponseEventsInner {
    /**
     *
     * @type {string}
     * @memberof CoderouterApiSandboxFileWatchPost200ResponseEventsInner
     */
    path: string;
    /**
     *
     * @type {string}
     * @memberof CoderouterApiSandboxFileWatchPost200ResponseEventsInner
     */
    type: CoderouterApiSandboxFileWatchPost200ResponseEventsInnerTypeEnum;
}

/**
 * @export
 */
export const CoderouterApiSandboxFileWatchPost200ResponseEventsInnerTypeEnum = {
    Create: 'create',
    Update: 'update',
    Delete: 'delete',
} as const;
export type CoderouterApiSandboxFileWatchPost200ResponseEventsInnerTypeEnum =
    (typeof CoderouterApiSandboxFileWatchPost200ResponseEventsInnerTypeEnum)[keyof typeof CoderouterApiSandboxFileWatchPost200ResponseEventsInnerTypeEnum];

/**
 * Check if a given object implements the CoderouterApiSandboxFileWatchPost200ResponseEventsInner interface.
 */
export function instanceOfCoderouterApiSandboxFileWatchPost200ResponseEventsInner(
    value: object,
): value is CoderouterApiSandboxFileWatchPost200ResponseEventsInner {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxFileWatchPost200ResponseEventsInnerFromJSON(
    json: any,
): CoderouterApiSandboxFileWatchPost200ResponseEventsInner {
    return CoderouterApiSandboxFileWatchPost200ResponseEventsInnerFromJSONTyped(json, false);
}

export function CoderouterApiSandboxFileWatchPost200ResponseEventsInnerFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxFileWatchPost200ResponseEventsInner {
    if (json == null) {
        return json;
    }
    return {
        path: json['path'],
        type: json['type'],
    };
}

export function CoderouterApiSandboxFileWatchPost200ResponseEventsInnerToJSON(
    json: any,
): CoderouterApiSandboxFileWatchPost200ResponseEventsInner {
    return CoderouterApiSandboxFileWatchPost200ResponseEventsInnerToJSONTyped(json, false);
}

export function CoderouterApiSandboxFileWatchPost200ResponseEventsInnerToJSONTyped(
    value?: CoderouterApiSandboxFileWatchPost200ResponseEventsInner | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        path: value['path'],
        type: value['type'],
    };
}
