/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxFileListPost200ResponseFilesInner
 */
export interface CoderouterApiSandboxFileListPost200ResponseFilesInner {
    /**
     *
     * @type {string}
     * @memberof CoderouterApiSandboxFileListPost200ResponseFilesInner
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof CoderouterApiSandboxFileListPost200ResponseFilesInner
     */
    path: string;
    /**
     *
     * @type {string}
     * @memberof CoderouterApiSandboxFileListPost200ResponseFilesInner
     */
    type: CoderouterApiSandboxFileListPost200ResponseFilesInnerTypeEnum;
}

/**
 * @export
 */
export const CoderouterApiSandboxFileListPost200ResponseFilesInnerTypeEnum = {
    File: 'file',
    Directory: 'directory',
} as const;
export type CoderouterApiSandboxFileListPost200ResponseFilesInnerTypeEnum =
    (typeof CoderouterApiSandboxFileListPost200ResponseFilesInnerTypeEnum)[keyof typeof CoderouterApiSandboxFileListPost200ResponseFilesInnerTypeEnum];

/**
 * Check if a given object implements the CoderouterApiSandboxFileListPost200ResponseFilesInner interface.
 */
export function instanceOfCoderouterApiSandboxFileListPost200ResponseFilesInner(
    value: object,
): value is CoderouterApiSandboxFileListPost200ResponseFilesInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxFileListPost200ResponseFilesInnerFromJSON(
    json: any,
): CoderouterApiSandboxFileListPost200ResponseFilesInner {
    return CoderouterApiSandboxFileListPost200ResponseFilesInnerFromJSONTyped(json, false);
}

export function CoderouterApiSandboxFileListPost200ResponseFilesInnerFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxFileListPost200ResponseFilesInner {
    if (json == null) {
        return json;
    }
    return {
        name: json['name'],
        path: json['path'],
        type: json['type'],
    };
}

export function CoderouterApiSandboxFileListPost200ResponseFilesInnerToJSON(
    json: any,
): CoderouterApiSandboxFileListPost200ResponseFilesInner {
    return CoderouterApiSandboxFileListPost200ResponseFilesInnerToJSONTyped(json, false);
}

export function CoderouterApiSandboxFileListPost200ResponseFilesInnerToJSONTyped(
    value?: CoderouterApiSandboxFileListPost200ResponseFilesInner | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value['name'],
        path: value['path'],
        type: value['type'],
    };
}
