/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxTerminalCommandPostRequest
 */
export interface CoderouterApiSandboxTerminalCommandPostRequest {
    /**
     * The command to run.
     * @type {string}
     * @memberof CoderouterApiSandboxTerminalCommandPostRequest
     */
    command: string;
}

/**
 * Check if a given object implements the CoderouterApiSandboxTerminalCommandPostRequest interface.
 */
export function instanceOfCoderouterApiSandboxTerminalCommandPostRequest(
    value: object,
): value is CoderouterApiSandboxTerminalCommandPostRequest {
    if (!('command' in value) || value['command'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxTerminalCommandPostRequestFromJSON(
    json: any,
): CoderouterApiSandboxTerminalCommandPostRequest {
    return CoderouterApiSandboxTerminalCommandPostRequestFromJSONTyped(json, false);
}

export function CoderouterApiSandboxTerminalCommandPostRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxTerminalCommandPostRequest {
    if (json == null) {
        return json;
    }
    return {
        command: json['command'],
    };
}

export function CoderouterApiSandboxTerminalCommandPostRequestToJSON(
    json: any,
): CoderouterApiSandboxTerminalCommandPostRequest {
    return CoderouterApiSandboxTerminalCommandPostRequestToJSONTyped(json, false);
}

export function CoderouterApiSandboxTerminalCommandPostRequestToJSONTyped(
    value?: CoderouterApiSandboxTerminalCommandPostRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        command: value['command'],
    };
}
