/* tslint:disable */
/* eslint-disable */
/**
 * Coderouter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CoderouterApiSandboxTerminalRunPostRequest
 */
export interface CoderouterApiSandboxTerminalRunPostRequest {
    /**
     * The ID of the terminal.
     * @type {string}
     * @memberof CoderouterApiSandboxTerminalRunPostRequest
     */
    terminalId: string;
    /**
     * The name of the terminal.
     * @type {string}
     * @memberof CoderouterApiSandboxTerminalRunPostRequest
     */
    input: string;
}

/**
 * Check if a given object implements the CoderouterApiSandboxTerminalRunPostRequest interface.
 */
export function instanceOfCoderouterApiSandboxTerminalRunPostRequest(
    value: object,
): value is CoderouterApiSandboxTerminalRunPostRequest {
    if (!('terminalId' in value) || value['terminalId'] === undefined) return false;
    if (!('input' in value) || value['input'] === undefined) return false;
    return true;
}

export function CoderouterApiSandboxTerminalRunPostRequestFromJSON(
    json: any,
): CoderouterApiSandboxTerminalRunPostRequest {
    return CoderouterApiSandboxTerminalRunPostRequestFromJSONTyped(json, false);
}

export function CoderouterApiSandboxTerminalRunPostRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CoderouterApiSandboxTerminalRunPostRequest {
    if (json == null) {
        return json;
    }
    return {
        terminalId: json['terminalId'],
        input: json['input'],
    };
}

export function CoderouterApiSandboxTerminalRunPostRequestToJSON(
    json: any,
): CoderouterApiSandboxTerminalRunPostRequest {
    return CoderouterApiSandboxTerminalRunPostRequestToJSONTyped(json, false);
}

export function CoderouterApiSandboxTerminalRunPostRequestToJSONTyped(
    value?: CoderouterApiSandboxTerminalRunPostRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        terminalId: value['terminalId'],
        input: value['input'],
    };
}
