import type { Metadata } from 'next'
import Script from 'next/script'

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link 
          rel="preconnect" 
          href="https://fonts.gstatic.com" 
          crossOrigin="anonymous" 
        />
        <Script
          src="https://cdn.jsdelivr.net/npm/theme-change@2.0.2/index.js"
          strategy="beforeInteractive"
        />
      </head>
      <body suppressHydrationWarning={true}>
        <div id="root">{children}</div>
      </body>
    </html>
  )
}