/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/eQ285HsN4Gx
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Sidebar } from "./sidebar"

export function Auth() {
  return (
    <div className="flex flex-row w-full h-full" data-oid="eom5yuc">
      <Sidebar data-oid="pw.swsl" />
      <div
        className="flex  w-full h-full items-center justify-center align-middle  "
        data-oid="oqes7o5"
      >
        <Card className="w-full mt-20 max-w-sm" data-oid="i_-imzw">
          <CardHeader data-oid="mn-u0sr">
            <CardTitle className="text-2xl" data-oid="0--2_9-">
              Login
            </CardTitle>
            <CardDescription data-oid="eipf1c_">
              Enter your email below to login to your account.
            </CardDescription>
          </CardHeader>
          <CardContent className="grid gap-4" data-oid="0r58s5p">
            <div className="grid gap-2" data-oid="p8s7gim">
              <Label htmlFor="email" data-oid="uvrj:ua">
                Email
              </Label>
              <Input
                id="email"
                placeholder="m@example.com"
                required
                type="email"
                data-oid="rjklu-q"
              />
            </div>
            <div className="grid gap-2" data-oid="2fge90w">
              <Label htmlFor="password" data-oid="2hnb86i">
                Password
              </Label>
              <Input
                id="password"
                required
                type="password"
                data-oid="fbrgy9q"
              />
            </div>
          </CardContent>
          <CardFooter data-oid="inv8bm8">
            <Button className="w-full" data-oid="vw08vzx">
              Sign in
            </Button>
          </CardFooter>
        </Card>
      </div>
    </div>
  )
}
