/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lTfKTcKU3Jd
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import {
  CardTitle,
  CardHeader,
  CardContent,
  Card,
  CardDescription,
} from "@/components/ui/card"
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table,
} from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Sidebar } from "./sidebar"

export function Orders() {
  return (
    <div className="flex min-h-screen w-full flex-row" data-oid="2v6duya">
      <Sidebar data-oid="4me9:ru" />
      <main
        className="ml-10 flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-8"
        data-oid="8zb1e0k"
      >
        <div
          className="grid gap-4 md:grid-cols-2 md:gap-8 lg:grid-cols-4"
          data-oid="0tr9z5c"
        >
          <Card x-chunk="dashboard-01-chunk-0" data-oid="4.v52ne">
            <CardHeader
              className="flex flex-row items-center justify-between space-y-0 pb-2"
              data-oid="llcau-:"
            >
              <CardTitle className="text-sm font-medium" data-oid="_yq.:_.">
                Total Revenue
              </CardTitle>
              <DollarSignIcon
                className="h-4 w-4 text-muted-foreground"
                data-oid="h9a_.mj"
              />
            </CardHeader>
            <CardContent data-oid="dr4u4oj">
              <div className="text-2xl font-bold" data-oid="66-b5ey">
                $45,231.89
              </div>
              <p className="text-xs text-muted-foreground" data-oid="cq6upfe">
                +20.1% from last month
              </p>
            </CardContent>
          </Card>
          <Card x-chunk="dashboard-01-chunk-1" data-oid="kyv2723">
            <CardHeader
              className="flex flex-row items-center justify-between space-y-0 pb-2"
              data-oid="9g95f84"
            >
              <CardTitle className="text-sm font-medium" data-oid="tnxmuc7">
                Subscriptions
              </CardTitle>
              <UsersIcon
                className="h-4 w-4 text-muted-foreground"
                data-oid=":8jz-3h"
              />
            </CardHeader>
            <CardContent data-oid="qyn6ua0">
              <div className="text-2xl font-bold" data-oid="7ebvoj.">
                +2350
              </div>
              <p className="text-xs text-muted-foreground" data-oid="csusafl">
                +180.1% from last month
              </p>
            </CardContent>
          </Card>
          <Card x-chunk="dashboard-01-chunk-2" data-oid="h-d3ma0">
            <CardHeader
              className="flex flex-row items-center justify-between space-y-0 pb-2"
              data-oid="f8.uzg0"
            >
              <CardTitle className="text-sm font-medium" data-oid="1vagrht">
                Sales
              </CardTitle>
              <CreditCardIcon
                className="h-4 w-4 text-muted-foreground"
                data-oid="8.xa2ed"
              />
            </CardHeader>
            <CardContent data-oid="4g--.zf">
              <div className="text-2xl font-bold" data-oid="80mo1il">
                +12,234
              </div>
              <p className="text-xs text-muted-foreground" data-oid="-d21_kj">
                +19% from last month
              </p>
            </CardContent>
          </Card>
          <Card x-chunk="dashboard-01-chunk-3" data-oid="hug:k1b">
            <CardHeader
              className="flex flex-row items-center justify-between space-y-0 pb-2"
              data-oid="otxvpsq"
            >
              <CardTitle className="text-sm font-medium" data-oid="2m6.rto">
                Active Now
              </CardTitle>
              <ActivityIcon
                className="h-4 w-4 text-muted-foreground"
                data-oid="z8rnu2s"
              />
            </CardHeader>
            <CardContent data-oid="d1-gqze">
              <div className="text-2xl font-bold" data-oid="s-33i4d">
                +573
              </div>
              <p className="text-xs text-muted-foreground" data-oid="tbod53p">
                +201 since last hour
              </p>
            </CardContent>
          </Card>
        </div>
        <div
          className="grid gap-4 md:gap-8 lg:grid-cols-2 xl:grid-cols-3"
          data-oid="mcvfrfn"
        >
          <Card
            className="xl:col-span-2"
            x-chunk="dashboard-01-chunk-4"
            data-oid="e9yco3h"
          >
            <CardHeader
              className="flex flex-row items-center"
              data-oid="lp:39w5"
            >
              <div className="grid gap-2" data-oid="z98.yq_">
                <CardTitle data-oid="0gedt.:">Transactions</CardTitle>
                <CardDescription data-oid="ho3m2q7">
                  Recent transactions from your store.
                </CardDescription>
              </div>
              <Button
                asChild
                className="ml-auto gap-1"
                size="sm"
                data-oid="1wgpw_j"
              >
                <Link href="#" data-oid="nl7vxu2">
                  View All
                  <ArrowUpRightIcon className="h-4 w-4" data-oid="p-nwdt5" />
                </Link>
              </Button>
            </CardHeader>
            <CardContent data-oid="ncyqe_w">
              <Table data-oid="9pqcobr">
                <TableHeader data-oid="yyq..i.">
                  <TableRow data-oid="q22tcgd">
                    <TableHead data-oid="5:7gh21">Customer</TableHead>
                    <TableHead
                      className="hidden xl:table-column"
                      data-oid="rzg7x-v"
                    >
                      Type
                    </TableHead>
                    <TableHead
                      className="hidden xl:table-column"
                      data-oid="j8twp54"
                    >
                      Status
                    </TableHead>
                    <TableHead
                      className="hidden xl:table-column"
                      data-oid="y8se-hg"
                    >
                      Date
                    </TableHead>
                    <TableHead className="text-right" data-oid="j0em.s_">
                      Amount
                    </TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody data-oid="n-e_67r">
                  <TableRow data-oid="4j.oo39">
                    <TableCell data-oid="nrqyigw">
                      <div className="font-medium" data-oid="oqn8j55">
                        Liam Johnson
                      </div>
                      <div
                        className="hidden text-sm text-muted-foreground md:inline"
                        data-oid=":a_oj-e"
                      >
                        liam@example.com
                      </div>
                    </TableCell>
                    <TableCell
                      className="hidden xl:table-column"
                      data-oid=":k0itlw"
                    >
                      Sale
                    </TableCell>
                    <TableCell
                      className="hidden xl:table-column"
                      data-oid="6ps3ztv"
                    >
                      <Badge
                        className="text-xs"
                        variant="outline"
                        data-oid="h89q._k"
                      >
                        Approved
                      </Badge>
                    </TableCell>
                    <TableCell
                      className="hidden md:table-cell lg:hidden xl:table-column"
                      data-oid="y1c2i2f"
                    >
                      2023-06-23
                    </TableCell>
                    <TableCell className="text-right" data-oid="ktmry.3">
                      $250.00
                    </TableCell>
                  </TableRow>
                  <TableRow data-oid="a3zfdst">
                    <TableCell data-oid="vhh0q7e">
                      <div className="font-medium" data-oid="tmc:3du">
                        Olivia Smith
                      </div>
                      <div
                        className="hidden text-sm text-muted-foreground md:inline"
                        data-oid="2-xr198"
                      >
                        olivia@example.com
                      </div>
                    </TableCell>
                    <TableCell
                      className="hidden xl:table-column"
                      data-oid="am:sd8h"
                    >
                      Refund
                    </TableCell>
                    <TableCell
                      className="hidden xl:table-column"
                      data-oid="zd_e1h5"
                    >
                      <Badge
                        className="text-xs"
                        variant="outline"
                        data-oid="skiayi:"
                      >
                        Declined
                      </Badge>
                    </TableCell>
                    <TableCell
                      className="hidden md:table-cell lg:hidden xl:table-column"
                      data-oid="ljt23gi"
                    >
                      2023-06-24
                    </TableCell>
                    <TableCell className="text-right" data-oid="z08.uyw">
                      $150.00
                    </TableCell>
                  </TableRow>
                  <TableRow data-oid="jay6q1t">
                    <TableCell data-oid="c_jwjhl">
                      <div className="font-medium" data-oid="pg6m34a">
                        Noah Williams
                      </div>
                      <div
                        className="hidden text-sm text-muted-foreground md:inline"
                        data-oid="c4zpevt"
                      >
                        noah@example.com
                      </div>
                    </TableCell>
                    <TableCell
                      className="hidden xl:table-column"
                      data-oid="b.-t24t"
                    >
                      Subscription
                    </TableCell>
                    <TableCell
                      className="hidden xl:table-column"
                      data-oid="e4gqvlu"
                    >
                      <Badge
                        className="text-xs"
                        variant="outline"
                        data-oid="p47-o1p"
                      >
                        Approved
                      </Badge>
                    </TableCell>
                    <TableCell
                      className="hidden md:table-cell lg:hidden xl:table-column"
                      data-oid="7e-z.dq"
                    >
                      2023-06-25
                    </TableCell>
                    <TableCell className="text-right" data-oid="t7gska2">
                      $350.00
                    </TableCell>
                  </TableRow>
                  <TableRow data-oid="tuemby_">
                    <TableCell data-oid="b-61ulp">
                      <div className="font-medium" data-oid="-cw3al6">
                        Emma Brown
                      </div>
                      <div
                        className="hidden text-sm text-muted-foreground md:inline"
                        data-oid="axdgtoc"
                      >
                        emma@example.com
                      </div>
                    </TableCell>
                    <TableCell
                      className="hidden xl:table-column"
                      data-oid="x7efoca"
                    >
                      Sale
                    </TableCell>
                    <TableCell
                      className="hidden xl:table-column"
                      data-oid="2h9alf3"
                    >
                      <Badge
                        className="text-xs"
                        variant="outline"
                        data-oid="6ag532u"
                      >
                        Approved
                      </Badge>
                    </TableCell>
                    <TableCell
                      className="hidden md:table-cell lg:hidden xl:table-column"
                      data-oid="rqc:3ul"
                    >
                      2023-06-26
                    </TableCell>
                    <TableCell className="text-right" data-oid="4_nioxb">
                      $450.00
                    </TableCell>
                  </TableRow>
                  <TableRow data-oid="jjeg6hb">
                    <TableCell data-oid="kjkp6fx">
                      <div className="font-medium" data-oid=".yz.i.s">
                        Liam Johnson
                      </div>
                      <div
                        className="hidden text-sm text-muted-foreground md:inline"
                        data-oid="5ve8hlz"
                      >
                        liam@example.com
                      </div>
                    </TableCell>
                    <TableCell
                      className="hidden xl:table-column"
                      data-oid=".mwp9wc"
                    >
                      Sale
                    </TableCell>
                    <TableCell
                      className="hidden xl:table-column"
                      data-oid="z:71un."
                    >
                      <Badge
                        className="text-xs"
                        variant="outline"
                        data-oid="qgu9269"
                      >
                        Approved
                      </Badge>
                    </TableCell>
                    <TableCell
                      className="hidden md:table-cell lg:hidden xl:table-column"
                      data-oid="-ydpq4g"
                    >
                      2023-06-27
                    </TableCell>
                    <TableCell className="text-right" data-oid="ctc7etz">
                      $550.00
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
          <Card x-chunk="dashboard-01-chunk-5" data-oid="yzqd-5m">
            <CardHeader data-oid="s04m61a">
              <CardTitle data-oid="ms0g6_w">Recent Sales</CardTitle>
            </CardHeader>
            <CardContent className="grid gap-8" data-oid="xblzfoe">
              <div className="flex items-center gap-4" data-oid="bo-mg0:">
                <Avatar className="hidden h-9 w-9 sm:flex" data-oid="8l_ir4p">
                  <AvatarImage
                    alt="Avatar"
                    src="/avatars/01.png"
                    data-oid="scictrx"
                  />

                  <AvatarFallback data-oid="98ot4zo">OM</AvatarFallback>
                </Avatar>
                <div className="grid gap-1" data-oid="pprbc1_">
                  <p
                    className="text-sm font-medium leading-none"
                    data-oid="jhzcq.b"
                  >
                    Olivia Martin
                  </p>
                  <p
                    className="text-sm text-muted-foreground"
                    data-oid="24gaoet"
                  >
                    olivia.martin@email.com
                  </p>
                </div>
                <div className="ml-auto font-medium" data-oid="hwwph9.">
                  +$1,999.00
                </div>
              </div>
              <div className="flex items-center gap-4" data-oid="7qwl0.b">
                <Avatar className="hidden h-9 w-9 sm:flex" data-oid=":0h:3sk">
                  <AvatarImage
                    alt="Avatar"
                    src="/avatars/02.png"
                    data-oid="yglywsz"
                  />

                  <AvatarFallback data-oid="-p-ytbf">JL</AvatarFallback>
                </Avatar>
                <div className="grid gap-1" data-oid="ifsbwgz">
                  <p
                    className="text-sm font-medium leading-none"
                    data-oid="cv6w_ev"
                  >
                    Jackson Lee
                  </p>
                  <p
                    className="text-sm text-muted-foreground"
                    data-oid="l3q5_nb"
                  >
                    jackson.lee@email.com
                  </p>
                </div>
                <div className="ml-auto font-medium" data-oid="i2b9k4:">
                  +$39.00
                </div>
              </div>
              <div className="flex items-center gap-4" data-oid="j-5p96x">
                <Avatar className="hidden h-9 w-9 sm:flex" data-oid="vq-0dni">
                  <AvatarImage
                    alt="Avatar"
                    src="/avatars/03.png"
                    data-oid="-7fqp0x"
                  />

                  <AvatarFallback data-oid="5uf3_fv">IN</AvatarFallback>
                </Avatar>
                <div className="grid gap-1" data-oid="fuk_4gx">
                  <p
                    className="text-sm font-medium leading-none"
                    data-oid="w9dmdxu"
                  >
                    Isabella Nguyen
                  </p>
                  <p
                    className="text-sm text-muted-foreground"
                    data-oid="ci6pquf"
                  >
                    isabella.nguyen@email.com
                  </p>
                </div>
                <div className="ml-auto font-medium" data-oid="l6q6j5n">
                  +$299.00
                </div>
              </div>
              <div className="flex items-center gap-4" data-oid="ock5a07">
                <Avatar className="hidden h-9 w-9 sm:flex" data-oid="_t12pwb">
                  <AvatarImage
                    alt="Avatar"
                    src="/avatars/04.png"
                    data-oid="y9m7j2h"
                  />

                  <AvatarFallback data-oid="d1f49ir">WK</AvatarFallback>
                </Avatar>
                <div className="grid gap-1" data-oid=":x.uwxp">
                  <p
                    className="text-sm font-medium leading-none"
                    data-oid="dmic24k"
                  >
                    William Kim
                  </p>
                  <p
                    className="text-sm text-muted-foreground"
                    data-oid="31q5.bb"
                  >
                    will@email.com
                  </p>
                </div>
                <div className="ml-auto font-medium" data-oid="p3-2vb3">
                  +$99.00
                </div>
              </div>
              <div className="flex items-center gap-4" data-oid="qarly70">
                <Avatar className="hidden h-9 w-9 sm:flex" data-oid="3ms3rf7">
                  <AvatarImage
                    alt="Avatar"
                    src="/avatars/05.png"
                    data-oid="xy89s.1"
                  />

                  <AvatarFallback data-oid="ane_q6w">SD</AvatarFallback>
                </Avatar>
                <div className="grid gap-1" data-oid="p3bhb25">
                  <p
                    className="text-sm font-medium leading-none"
                    data-oid="dvvgfwa"
                  >
                    Sofia Davis
                  </p>
                  <p
                    className="text-sm text-muted-foreground"
                    data-oid="6mwkza0"
                  >
                    sofia.davis@email.com
                  </p>
                </div>
                <div className="ml-auto font-medium" data-oid="59_f1vg">
                  +$39.00
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}

function ActivityIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="1jy6n00"
    >
      <path
        d="M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2"
        data-oid="nnb4tew"
      />
    </svg>
  )
}

function ArrowUpRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="t4j48xd"
    >
      <path d="M7 7h10v10" data-oid="1ttk7vr" />
      <path d="M7 17 17 7" data-oid="ci9:2o_" />
    </svg>
  )
}

function CircleUserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="7su83v2"
    >
      <circle cx="12" cy="12" r="10" data-oid="akahac8" />
      <circle cx="12" cy="10" r="3" data-oid="gvt2ig5" />
      <path
        d="M7 20.662V19a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v1.662"
        data-oid="y_t0hli"
      />
    </svg>
  )
}

function CreditCardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="kgnp8a6"
    >
      <rect width="20" height="14" x="2" y="5" rx="2" data-oid="4pblupt" />
      <line x1="2" x2="22" y1="10" y2="10" data-oid="j2jn3gf" />
    </svg>
  )
}

function DollarSignIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="as7_:oc"
    >
      <line x1="12" x2="12" y1="2" y2="22" data-oid="wmg_5-k" />
      <path
        d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"
        data-oid="g.ho:mj"
      />
    </svg>
  )
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="i.y2_o."
    >
      <line x1="4" x2="20" y1="12" y2="12" data-oid="cctdwws" />
      <line x1="4" x2="20" y1="6" y2="6" data-oid="sd0wpoc" />
      <line x1="4" x2="20" y1="18" y2="18" data-oid="vmg-mxz" />
    </svg>
  )
}

function Package2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="eog-2b6"
    >
      <path
        d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z"
        data-oid="y64629p"
      />

      <path
        d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9"
        data-oid="-70dmsn"
      />

      <path d="M12 3v6" data-oid="w:u7:1j" />
    </svg>
  )
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="14.fbmq"
    >
      <circle cx="11" cy="11" r="8" data-oid="ui2m:ol" />
      <path d="m21 21-4.3-4.3" data-oid="0y26o9z" />
    </svg>
  )
}

function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="etei4i_"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" data-oid="e25xoq0" />
      <circle cx="9" cy="7" r="4" data-oid="s:p1np6" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" data-oid="n5--ipu" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" data-oid="-bt6.kj" />
    </svg>
  )
}
