/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/oLjAqCceubI
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { SheetTrigger, SheetContent, Sheet } from "@/components/ui/sheet"
import {
  BreadcrumbLink,
  BreadcrumbItem,
  BreadcrumbSeparator,
  BreadcrumbPage,
  BreadcrumbList,
  Breadcrumb,
} from "@/components/ui/breadcrumb"
import { Input } from "@/components/ui/input"
import {
  DropdownMenuTrigger,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuItem,
  DropdownMenuContent,
  DropdownMenu,
  DropdownMenuCheckboxItem,
} from "@/components/ui/dropdown-menu"
import { TabsTrigger, TabsList, TabsContent, Tabs } from "@/components/ui/tabs"
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card"
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table,
} from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { Sidebar } from "./sidebar"

export function Products() {
  return (
    <div
      className="flex min-h-screen w-full flex-col bg-muted/40"
      data-oid="i59kaq:"
    >
      <Sidebar data-oid="hszdn46" />
      <div
        className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14"
        data-oid="pp975ej"
      >
        <header
          className="sticky top-0 z-30 flex h-14 items-center gap-4 border-b bg-background px-4 sm:static sm:h-auto sm:border-0 sm:bg-transparent sm:px-6"
          data-oid="ya0ypqi"
        >
          <Sheet data-oid="ey83rpc">
            <SheetTrigger asChild data-oid="f82eovn">
              <Button
                className="sm:hidden"
                size="icon"
                variant="outline"
                data-oid="c4s0qsf"
              >
                <PanelLeftIcon className="h-5 w-5" data-oid="u_b.:-k" />
                <span className="sr-only" data-oid="rsel2.4">
                  Toggle Menu
                </span>
              </Button>
            </SheetTrigger>
            <SheetContent
              className="sm:max-w-xs"
              side="left"
              data-oid="mnwt_ac"
            >
              <nav
                className="grid gap-6 text-lg font-medium"
                data-oid="d27w8cn"
              >
                <Link
                  className="group flex h-10 w-10 shrink-0 items-center justify-center gap-2 rounded-full bg-primary text-lg font-semibold text-primary-foreground md:text-base"
                  href="#"
                  data-oid="eswrzj3"
                >
                  <Package2Icon
                    className="h-5 w-5 transition-all group-hover:scale-110"
                    data-oid="sur0t8r"
                  />

                  <span className="sr-only" data-oid="59lodk8">
                    Acme Inc
                  </span>
                </Link>
                <Link
                  className="flex items-center gap-4 px-2.5 text-muted-foreground hover:text-foreground"
                  href="#"
                  data-oid="2kkwakd"
                >
                  <HomeIcon className="h-5 w-5" data-oid="jpr0a6n" />
                  Dashboard
                </Link>
                <Link
                  className="flex items-center gap-4 px-2.5 text-muted-foreground hover:text-foreground"
                  href="#"
                  data-oid="jjt57w:"
                >
                  <ShoppingCartIcon className="h-5 w-5" data-oid=".175e10" />
                  Orders
                </Link>
                <Link
                  className="flex items-center gap-4 px-2.5 text-foreground"
                  href="#"
                  data-oid="k8:0jus"
                >
                  <PackageIcon className="h-5 w-5" data-oid="p7gm:ad" />
                  Products
                </Link>
                <Link
                  className="flex items-center gap-4 px-2.5 text-muted-foreground hover:text-foreground"
                  href="#"
                  data-oid="i43xcmn"
                >
                  <UsersIcon className="h-5 w-5" data-oid="9r5h6gx" />
                  Customers
                </Link>
                <Link
                  className="flex items-center gap-4 px-2.5 text-muted-foreground hover:text-foreground"
                  href="#"
                  data-oid="yvx1xxk"
                >
                  <LineChartIcon className="h-5 w-5" data-oid="aqt854o" />
                  Settings
                </Link>
              </nav>
            </SheetContent>
          </Sheet>
          <Breadcrumb className="hidden md:flex" data-oid="1e637qg">
            <BreadcrumbList data-oid="9cl.0rh">
              <BreadcrumbItem data-oid="37osr_l">
                <BreadcrumbLink asChild data-oid="8hgmz-c">
                  <Link href="#" data-oid="cqw4f:u">
                    Dashboard
                  </Link>
                </BreadcrumbLink>
              </BreadcrumbItem>
              <BreadcrumbSeparator data-oid="7o421-g" />
              <BreadcrumbItem data-oid="yc:h6ie">
                <BreadcrumbLink asChild data-oid="8wogvj0">
                  <Link href="#" data-oid="q98so:z">
                    Products
                  </Link>
                </BreadcrumbLink>
              </BreadcrumbItem>
              <BreadcrumbSeparator data-oid="nki6tql" />
              <BreadcrumbItem data-oid="mef:itf">
                <BreadcrumbPage data-oid="rs5h.0q">All Products</BreadcrumbPage>
              </BreadcrumbItem>
            </BreadcrumbList>
          </Breadcrumb>
          <div className="relative ml-auto flex-1 md:grow-0" data-oid="y-i2p8q">
            <SearchIcon
              className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground"
              data-oid="0j-f82p"
            />

            <Input
              className="w-full rounded-lg bg-background pl-8 md:w-[200px] lg:w-[336px]"
              placeholder="Search..."
              type="search"
              data-oid="46ekgmj"
            />
          </div>
          <DropdownMenu data-oid="a1zww3s">
            <DropdownMenuTrigger asChild data-oid="c9.-3u2">
              <Button
                className="overflow-hidden rounded-full"
                size="icon"
                variant="outline"
                data-oid="3x5uu2:"
              >
                <img
                  alt="Avatar"
                  className="overflow-hidden rounded-full"
                  height={36}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "36/36",
                    objectFit: "cover",
                  }}
                  width={36}
                  data-oid="ljd7hxl"
                />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" data-oid="9wq..u2">
              <DropdownMenuLabel data-oid="a1.aiju">
                My Account
              </DropdownMenuLabel>
              <DropdownMenuSeparator data-oid="qtuy_ic" />
              <DropdownMenuItem data-oid="xvjysw0">Settings</DropdownMenuItem>
              <DropdownMenuItem data-oid="nait7.:">Support</DropdownMenuItem>
              <DropdownMenuSeparator data-oid="_mywaee" />
              <DropdownMenuItem data-oid="yeo8en0">Logout</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </header>
        <main
          className="grid flex-1 items-start gap-4 p-4 sm:px-6 sm:py-0 md:gap-8"
          data-oid="a4fcck_"
        >
          <Tabs defaultValue="all" data-oid="16-6i7.">
            <div className="flex items-center" data-oid="gs6v1c1">
              <TabsList data-oid="fdj9..c">
                <TabsTrigger value="all" data-oid="xb0wz4w">
                  All
                </TabsTrigger>
                <TabsTrigger value="active" data-oid="ixb8o38">
                  Active
                </TabsTrigger>
                <TabsTrigger value="draft" data-oid="f84t059">
                  Draft
                </TabsTrigger>
                <TabsTrigger
                  className="hidden sm:flex"
                  value="archived"
                  data-oid="wvzufh:"
                >
                  Archived
                </TabsTrigger>
              </TabsList>
              <div
                className="ml-auto flex items-center gap-2"
                data-oid="ul3r:hn"
              >
                <DropdownMenu data-oid="3w7xfep">
                  <DropdownMenuTrigger asChild data-oid="j:mj6:m">
                    <Button
                      className="h-8 gap-1"
                      size="sm"
                      variant="outline"
                      data-oid="7ejphmb"
                    >
                      <ListFilterIcon
                        className="h-3.5 w-3.5"
                        data-oid="l6g9j28"
                      />

                      <span
                        className="sr-only sm:not-sr-only sm:whitespace-nowrap"
                        data-oid="_nnl_gy"
                      >
                        Filter
                      </span>
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end" data-oid="dpqt:8m">
                    <DropdownMenuLabel data-oid="kerxhkb">
                      Filter by
                    </DropdownMenuLabel>
                    <DropdownMenuSeparator data-oid="rj6li:r" />
                    <DropdownMenuCheckboxItem checked data-oid="8usj38q">
                      Active
                    </DropdownMenuCheckboxItem>
                    <DropdownMenuCheckboxItem data-oid="41d-1rm">
                      Draft
                    </DropdownMenuCheckboxItem>
                    <DropdownMenuCheckboxItem data-oid="hwnpq8t">
                      Archived
                    </DropdownMenuCheckboxItem>
                  </DropdownMenuContent>
                </DropdownMenu>
                <Button
                  className="h-8 gap-1"
                  size="sm"
                  variant="outline"
                  data-oid="u7zfcet"
                >
                  <FileIcon className="h-3.5 w-3.5" data-oid="7ly.v_l" />
                  <span
                    className="sr-only sm:not-sr-only sm:whitespace-nowrap"
                    data-oid=".t76lq-"
                  >
                    Export
                  </span>
                </Button>
                <Button className="h-8 gap-1" size="sm" data-oid="iywlhh5">
                  <CirclePlusIcon className="h-3.5 w-3.5" data-oid="tg2ufl_" />
                  <span
                    className="sr-only sm:not-sr-only sm:whitespace-nowrap"
                    data-oid="3ed1ml."
                  >
                    Add Product
                  </span>
                </Button>
              </div>
            </div>
            <TabsContent value="all" data-oid="cz7t7ky">
              <Card x-chunk="dashboard-06-chunk-0" data-oid="a_-c5ej">
                <CardHeader data-oid=".rtmvca">
                  <CardTitle data-oid="z3q5iwa">Products</CardTitle>
                  <CardDescription data-oid="7pps6g7">
                    Manage your products and view their sales performance.
                  </CardDescription>
                </CardHeader>
                <CardContent data-oid=".2h665l">
                  <Table data-oid="500_woh">
                    <TableHeader data-oid="s9om5va">
                      <TableRow data-oid="7bz5d00">
                        <TableHead
                          className="hidden w-[100px] sm:table-cell"
                          data-oid="wr5rx55"
                        >
                          <span className="sr-only" data-oid="u5nq__g">
                            Image
                          </span>
                        </TableHead>
                        <TableHead data-oid="wrpf_-x">Name</TableHead>
                        <TableHead data-oid="j:lytx-">Status</TableHead>
                        <TableHead
                          className="hidden md:table-cell"
                          data-oid="cn-ujc-"
                        >
                          Price
                        </TableHead>
                        <TableHead
                          className="hidden md:table-cell"
                          data-oid="5cdqh96"
                        >
                          Total Sales
                        </TableHead>
                        <TableHead
                          className="hidden md:table-cell"
                          data-oid="gffc5kq"
                        >
                          Created at
                        </TableHead>
                        <TableHead data-oid="cli8cme">
                          <span className="sr-only" data-oid=".ftfqu8">
                            Actions
                          </span>
                        </TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody data-oid="xdnma6-">
                      <TableRow data-oid="60qyd:2">
                        <TableCell
                          className="hidden sm:table-cell"
                          data-oid="mu8ex4y"
                        >
                          <img
                            alt="Product image"
                            className="aspect-square rounded-md object-cover"
                            height="64"
                            src="/placeholder.svg"
                            width="64"
                            data-oid="10tux6m"
                          />
                        </TableCell>
                        <TableCell className="font-medium" data-oid="z.ve.yh">
                          Laser Lemonade Machine
                        </TableCell>
                        <TableCell data-oid="p5p_28k">
                          <Badge variant="outline" data-oid="vft-cc-">
                            Draft
                          </Badge>
                        </TableCell>
                        <TableCell
                          className="hidden md:table-cell"
                          data-oid="2o_:d4o"
                        >
                          $499.99
                        </TableCell>
                        <TableCell
                          className="hidden md:table-cell"
                          data-oid="7jjw2tr"
                        >
                          25
                        </TableCell>
                        <TableCell
                          className="hidden md:table-cell"
                          data-oid="j4fhohv"
                        >
                          2023-07-12 10:42 AM
                        </TableCell>
                        <TableCell data-oid="7ff4y56">
                          <DropdownMenu data-oid="c-yf9vc">
                            <DropdownMenuTrigger asChild data-oid="_cfko0v">
                              <Button
                                aria-haspopup="true"
                                size="icon"
                                variant="ghost"
                                data-oid="gj0xotz"
                              >
                                <MoveHorizontalIcon
                                  className="h-4 w-4"
                                  data-oid="9chke48"
                                />

                                <span className="sr-only" data-oid="kk2dg5j">
                                  Toggle menu
                                </span>
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end" data-oid="51rbvtk">
                              <DropdownMenuLabel data-oid="w23q9xr">
                                Actions
                              </DropdownMenuLabel>
                              <DropdownMenuItem data-oid="_0at:rk">
                                Edit
                              </DropdownMenuItem>
                              <DropdownMenuItem data-oid="7-mgdfy">
                                Delete
                              </DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </TableCell>
                      </TableRow>
                      <TableRow data-oid="5nom00a">
                        <TableCell
                          className="hidden sm:table-cell"
                          data-oid="mgm568e"
                        >
                          <img
                            alt="Product image"
                            className="aspect-square rounded-md object-cover"
                            height="64"
                            src="/placeholder.svg"
                            width="64"
                            data-oid="scj7ffa"
                          />
                        </TableCell>
                        <TableCell className="font-medium" data-oid=".dw3rj3">
                          Hypernova Headphones
                        </TableCell>
                        <TableCell data-oid="ol-7t48">
                          <Badge variant="outline" data-oid="j3c:0iw">
                            Active
                          </Badge>
                        </TableCell>
                        <TableCell
                          className="hidden md:table-cell"
                          data-oid="zddghuu"
                        >
                          $129.99
                        </TableCell>
                        <TableCell
                          className="hidden md:table-cell"
                          data-oid="9-mjk81"
                        >
                          100
                        </TableCell>
                        <TableCell
                          className="hidden md:table-cell"
                          data-oid="xb8jvx6"
                        >
                          2023-10-18 03:21 PM
                        </TableCell>
                        <TableCell data-oid="djs:3gd">
                          <DropdownMenu data-oid="wepc1:c">
                            <DropdownMenuTrigger asChild data-oid=":os2.4u">
                              <Button
                                aria-haspopup="true"
                                size="icon"
                                variant="ghost"
                                data-oid="6hvkhex"
                              >
                                <MoveHorizontalIcon
                                  className="h-4 w-4"
                                  data-oid="80lc:ri"
                                />

                                <span className="sr-only" data-oid="ycqot-u">
                                  Toggle menu
                                </span>
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end" data-oid="spc2lfu">
                              <DropdownMenuLabel data-oid="xhex84p">
                                Actions
                              </DropdownMenuLabel>
                              <DropdownMenuItem data-oid="v5jf:ms">
                                Edit
                              </DropdownMenuItem>
                              <DropdownMenuItem data-oid="t030vo-">
                                Delete
                              </DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </TableCell>
                      </TableRow>
                      <TableRow data-oid="2zt4rkw">
                        <TableCell
                          className="hidden sm:table-cell"
                          data-oid="icgywf8"
                        >
                          <img
                            alt="Product image"
                            className="aspect-square rounded-md object-cover"
                            height="64"
                            src="/placeholder.svg"
                            width="64"
                            data-oid="935qkd1"
                          />
                        </TableCell>
                        <TableCell className="font-medium" data-oid="3swh.fu">
                          AeroGlow Desk Lamp
                        </TableCell>
                        <TableCell data-oid="2cv7y5g">
                          <Badge variant="outline" data-oid="sfj39-h">
                            Active
                          </Badge>
                        </TableCell>
                        <TableCell
                          className="hidden md:table-cell"
                          data-oid="2ptnz6x"
                        >
                          $39.99
                        </TableCell>
                        <TableCell
                          className="hidden md:table-cell"
                          data-oid="nb42lnp"
                        >
                          50
                        </TableCell>
                        <TableCell
                          className="hidden md:table-cell"
                          data-oid=".vscaus"
                        >
                          2023-11-29 08:15 AM
                        </TableCell>
                        <TableCell data-oid="c8ed-cl">
                          <DropdownMenu data-oid=":-htaha">
                            <DropdownMenuTrigger asChild data-oid="sq8_amd">
                              <Button
                                aria-haspopup="true"
                                size="icon"
                                variant="ghost"
                                data-oid="dxf-oyx"
                              >
                                <MoveHorizontalIcon
                                  className="h-4 w-4"
                                  data-oid="w5v.zft"
                                />

                                <span className="sr-only" data-oid="a8ezinr">
                                  Toggle menu
                                </span>
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end" data-oid="a917l8s">
                              <DropdownMenuLabel data-oid="ih-dymu">
                                Actions
                              </DropdownMenuLabel>
                              <DropdownMenuItem data-oid="k0hylyg">
                                Edit
                              </DropdownMenuItem>
                              <DropdownMenuItem data-oid="0f4a_0x">
                                Delete
                              </DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </TableCell>
                      </TableRow>
                      <TableRow data-oid="406uqgx">
                        <TableCell
                          className="hidden sm:table-cell"
                          data-oid=".kufi3u"
                        >
                          <img
                            alt="Product image"
                            className="aspect-square rounded-md object-cover"
                            height="64"
                            src="/placeholder.svg"
                            width="64"
                            data-oid=".4t01qc"
                          />
                        </TableCell>
                        <TableCell className="font-medium" data-oid="2-wl9x2">
                          TechTonic Energy Drink
                        </TableCell>
                        <TableCell data-oid="yei-d.k">
                          <Badge variant="secondary" data-oid="e_.4ph5">
                            Draft
                          </Badge>
                        </TableCell>
                        <TableCell
                          className="hidden md:table-cell"
                          data-oid="c1l22pp"
                        >
                          $2.99
                        </TableCell>
                        <TableCell
                          className="hidden md:table-cell"
                          data-oid="bwqciai"
                        >
                          0
                        </TableCell>
                        <TableCell
                          className="hidden md:table-cell"
                          data-oid="z_ehrf4"
                        >
                          2023-12-25 11:59 PM
                        </TableCell>
                        <TableCell data-oid="a.ap_yk">
                          <DropdownMenu data-oid="c8e8eux">
                            <DropdownMenuTrigger asChild data-oid="l-_6tvn">
                              <Button
                                aria-haspopup="true"
                                size="icon"
                                variant="ghost"
                                data-oid="t1m0dhe"
                              >
                                <MoveHorizontalIcon
                                  className="h-4 w-4"
                                  data-oid="m955hs_"
                                />

                                <span className="sr-only" data-oid="a:hfk.4">
                                  Toggle menu
                                </span>
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end" data-oid="hn69w2k">
                              <DropdownMenuLabel data-oid="idjmr97">
                                Actions
                              </DropdownMenuLabel>
                              <DropdownMenuItem data-oid="0jk.eqe">
                                Edit
                              </DropdownMenuItem>
                              <DropdownMenuItem data-oid="is2d:4f">
                                Delete
                              </DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </TableCell>
                      </TableRow>
                      <TableRow data-oid="xk2pep9">
                        <TableCell
                          className="hidden sm:table-cell"
                          data-oid="-bf_a43"
                        >
                          <img
                            alt="Product image"
                            className="aspect-square rounded-md object-cover"
                            height="64"
                            src="/placeholder.svg"
                            width="64"
                            data-oid="3w4uq0k"
                          />
                        </TableCell>
                        <TableCell className="font-medium" data-oid="gcu3qlx">
                          Gamer Gear Pro Controller
                        </TableCell>
                        <TableCell data-oid="iru2ep5">
                          <Badge variant="outline" data-oid="jdfzsra">
                            Active
                          </Badge>
                        </TableCell>
                        <TableCell
                          className="hidden md:table-cell"
                          data-oid="hqf4i9r"
                        >
                          $59.99
                        </TableCell>
                        <TableCell
                          className="hidden md:table-cell"
                          data-oid="1mbmepu"
                        >
                          75
                        </TableCell>
                        <TableCell
                          className="hidden md:table-cell"
                          data-oid="d_q2bvf"
                        >
                          2024-01-01 12:00 AM
                        </TableCell>
                        <TableCell data-oid="4qtr-u-">
                          <DropdownMenu data-oid="u_.on4w">
                            <DropdownMenuTrigger asChild data-oid="yygfr-c">
                              <Button
                                aria-haspopup="true"
                                size="icon"
                                variant="ghost"
                                data-oid="2tutcwm"
                              >
                                <MoveHorizontalIcon
                                  className="h-4 w-4"
                                  data-oid="xiuvx6h"
                                />

                                <span className="sr-only" data-oid="s9pd55r">
                                  Toggle menu
                                </span>
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end" data-oid="6lg:.j5">
                              <DropdownMenuLabel data-oid="yc_tzcv">
                                Actions
                              </DropdownMenuLabel>
                              <DropdownMenuItem data-oid="xmsdq_v">
                                Edit
                              </DropdownMenuItem>
                              <DropdownMenuItem data-oid="sfl.-fd">
                                Delete
                              </DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </TableCell>
                      </TableRow>
                      <TableRow data-oid="2hway5u">
                        <TableCell
                          className="hidden sm:table-cell"
                          data-oid="wjp-3i5"
                        >
                          <img
                            alt="Product image"
                            className="aspect-square rounded-md object-cover"
                            height="64"
                            src="/placeholder.svg"
                            width="64"
                            data-oid="7w2dvx:"
                          />
                        </TableCell>
                        <TableCell className="font-medium" data-oid="h62eyia">
                          Luminous VR Headset
                        </TableCell>
                        <TableCell data-oid="_5t6l.l">
                          <Badge variant="outline" data-oid="c6mldel">
                            Active
                          </Badge>
                        </TableCell>
                        <TableCell
                          className="hidden md:table-cell"
                          data-oid="o_.nt5l"
                        >
                          $199.99
                        </TableCell>
                        <TableCell
                          className="hidden md:table-cell"
                          data-oid="pfl2xgh"
                        >
                          30
                        </TableCell>
                        <TableCell
                          className="hidden md:table-cell"
                          data-oid="4o6x3yy"
                        >
                          2024-02-14 02:14 PM
                        </TableCell>
                        <TableCell data-oid="ceqpokv">
                          <DropdownMenu data-oid="nfzyqg8">
                            <DropdownMenuTrigger asChild data-oid="qugw1tf">
                              <Button
                                aria-haspopup="true"
                                size="icon"
                                variant="ghost"
                                data-oid="o8s8j1-"
                              >
                                <MoveHorizontalIcon
                                  className="h-4 w-4"
                                  data-oid="5xv:7-u"
                                />

                                <span className="sr-only" data-oid="tgjd9-m">
                                  Toggle menu
                                </span>
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end" data-oid="_-h3vi8">
                              <DropdownMenuLabel data-oid="zsjh66w">
                                Actions
                              </DropdownMenuLabel>
                              <DropdownMenuItem data-oid="c4.0f1k">
                                Edit
                              </DropdownMenuItem>
                              <DropdownMenuItem data-oid="-3kw585">
                                Delete
                              </DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </CardContent>
                <CardFooter data-oid="6xy-55h">
                  <div
                    className="text-xs text-muted-foreground"
                    data-oid="6::od_c"
                  >
                    Showing
                    <strong data-oid="7x1etxp">1-10</strong> of{" "}
                    <strong data-oid="og1v.ix">32</strong>
                    products
                  </div>
                </CardFooter>
              </Card>
            </TabsContent>
          </Tabs>
        </main>
      </div>
    </div>
  )
}

function CirclePlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid=":z-zfkp"
    >
      <circle cx="12" cy="12" r="10" data-oid="6ee26a:" />
      <path d="M8 12h8" data-oid="vd3gxvb" />
      <path d="M12 8v8" data-oid="aox1qqh" />
    </svg>
  )
}

function FileIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="bjd_40u"
    >
      <path
        d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"
        data-oid="u0l-0:r"
      />

      <path d="M14 2v4a2 2 0 0 0 2 2h4" data-oid="2k9onq-" />
    </svg>
  )
}

function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="cy6l75k"
    >
      <path
        d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"
        data-oid="vu9xwts"
      />

      <polyline points="9 22 9 12 15 12 15 22" data-oid="mb7__bi" />
    </svg>
  )
}

function LineChartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="tno.mcc"
    >
      <path d="M3 3v18h18" data-oid="e4v1.fq" />
      <path d="m19 9-5 5-4-4-3 3" data-oid="bxvql43" />
    </svg>
  )
}

function ListFilterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="ro9yn_p"
    >
      <path d="M3 6h18" data-oid="11j027l" />
      <path d="M7 12h10" data-oid="gh33l5s" />
      <path d="M10 18h4" data-oid=".ze2k6l" />
    </svg>
  )
}

function MoveHorizontalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="gmls_8s"
    >
      <polyline points="18 8 22 12 18 16" data-oid="0rueizs" />
      <polyline points="6 8 2 12 6 16" data-oid="6qczzy5" />
      <line x1="2" x2="22" y1="12" y2="12" data-oid="kg7vhwg" />
    </svg>
  )
}

function Package2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="pcx.bpk"
    >
      <path
        d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z"
        data-oid="6xfeib1"
      />

      <path
        d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9"
        data-oid="jdtmcd1"
      />

      <path d="M12 3v6" data-oid="s3v2puk" />
    </svg>
  )
}

function PackageIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid=".qnn.jk"
    >
      <path d="m7.5 4.27 9 5.15" data-oid="gd.-lzo" />
      <path
        d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z"
        data-oid="lvdzfij"
      />

      <path d="m3.3 7 8.7 5 8.7-5" data-oid="782:77e" />
      <path d="M12 22V12" data-oid="m5.b7e." />
    </svg>
  )
}

function PanelLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="e0z_hcg"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" data-oid="h-frr-y" />
      <path d="M9 3v18" data-oid="1t7x0rw" />
    </svg>
  )
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="iptehdg"
    >
      <circle cx="11" cy="11" r="8" data-oid="6buztqo" />
      <path d="m21 21-4.3-4.3" data-oid=":1c3ldu" />
    </svg>
  )
}

function SettingsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="ke.uefr"
    >
      <path
        d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"
        data-oid="cqm0_tj"
      />

      <circle cx="12" cy="12" r="3" data-oid="-kc_-ay" />
    </svg>
  )
}

function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="no1ewr3"
    >
      <circle cx="8" cy="21" r="1" data-oid="2wj0g.9" />
      <circle cx="19" cy="21" r="1" data-oid="1pjdp39" />
      <path
        d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12"
        data-oid="lvr_rs_"
      />
    </svg>
  )
}

function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="95w4lag"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" data-oid="ro3yo4u" />
      <circle cx="9" cy="7" r="4" data-oid="p7m7y7a" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" data-oid="lv4mmll" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" data-oid="tytelip" />
    </svg>
  )
}
