/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HlSXJZthgSR
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card"
import { Checkbox } from "@/components/ui/checkbox"
import { Sidebar } from "./sidebar"

export function Settings() {
  return (
    <div className="flex min-h-screen w-full flex-row" data-oid="ea77ner">
      <Sidebar data-oid="ye38j5." />
      <main
        className="ml-10 flex min-h-[calc(100vh_-_theme(spacing.16))] flex-1 flex-col gap-4 bg-muted/40 p-4 md:gap-8 md:p-10"
        data-oid="lotc4:h"
      >
        <div className="mx-auto grid w-full max-w-6xl gap-2" data-oid="r-wnb0s">
          <h1 className="text-3xl font-semibold" data-oid="-xoky-p">
            Settings
          </h1>
        </div>
        <div
          className="mx-auto grid w-full max-w-6xl items-start gap-6 md:grid-cols-[180px_1fr] lg:grid-cols-[250px_1fr]"
          data-oid="10f6t7c"
        >
          <nav
            className="grid gap-4 text-sm text-muted-foreground"
            x-chunk="dashboard-04-chunk-0"
            data-oid="1cxb0gx"
          >
            <Link
              className="font-semibold text-primary"
              href="#"
              data-oid="uurfzex"
            >
              General
            </Link>
            <Link href="#" data-oid="d:shxg7">
              Security
            </Link>
            <Link href="#" data-oid=":veeprv">
              Integrations
            </Link>
            <Link href="#" data-oid="_h:k9eo">
              Support
            </Link>
            <Link href="#" data-oid="7vzl-1y">
              Organizations
            </Link>
            <Link href="#" data-oid="6ll:zhv">
              Advanced
            </Link>
          </nav>
          <div className="grid gap-6" data-oid="-r56oap">
            <Card x-chunk="dashboard-04-chunk-1" data-oid=".s4r5_i">
              <CardHeader data-oid="1lg_ptl">
                <CardTitle data-oid="_g9011k">Store Name</CardTitle>
                <CardDescription data-oid="ml1vukr">
                  Used to identify your store in the marketplace.
                </CardDescription>
              </CardHeader>
              <CardContent data-oid="ab8f2hx">
                <form data-oid=".khsa1m">
                  <Input placeholder="Store Name" data-oid="0l27k8h" />
                </form>
              </CardContent>
              <CardFooter className="border-t px-6 py-4" data-oid="w8v5at9">
                <Button data-oid="lk:nga9">Save</Button>
              </CardFooter>
            </Card>
            <Card x-chunk="dashboard-04-chunk-2" data-oid="_c-dvrv">
              <CardHeader data-oid="29:67_2">
                <CardTitle data-oid="3squyl4">Plugins Directory</CardTitle>
                <CardDescription data-oid="vecv1ym">
                  The directory within your project, in which your plugins are
                  located.
                </CardDescription>
              </CardHeader>
              <CardContent data-oid="grcx-:5">
                <form className="flex flex-col gap-4" data-oid="vl9at:_">
                  <Input
                    defaultValue="/content/plugins"
                    placeholder="Project Name"
                    data-oid="dx-7..7"
                  />

                  <div
                    className="flex items-center space-x-2"
                    data-oid="7jv-3ho"
                  >
                    <Checkbox defaultChecked id="include" data-oid="ozb0aot" />
                    <label
                      className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
                      htmlFor="include"
                      data-oid="oa-.1.."
                    >
                      Allow administrators to change the directory.
                    </label>
                  </div>
                </form>
              </CardContent>
              <CardFooter className="border-t px-6 py-4" data-oid="hvdagk-">
                <Button data-oid="f.n2lm-">Save</Button>
              </CardFooter>
            </Card>
          </div>
        </div>
      </main>
    </div>
  )
}

function CircleUserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="4b0v6ke"
    >
      <circle cx="12" cy="12" r="10" data-oid="01_fc-7" />
      <circle cx="12" cy="10" r="3" data-oid="vs5v32v" />
      <path
        d="M7 20.662V19a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v1.662"
        data-oid="_q.f6ke"
      />
    </svg>
  )
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="0xd:4t6"
    >
      <line x1="4" x2="20" y1="12" y2="12" data-oid="auveh4o" />
      <line x1="4" x2="20" y1="6" y2="6" data-oid="t1:qfbh" />
      <line x1="4" x2="20" y1="18" y2="18" data-oid="z45fm2o" />
    </svg>
  )
}

function Package2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="kxqwfj7"
    >
      <path
        d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z"
        data-oid="uc8.02."
      />

      <path
        d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9"
        data-oid="8ikmr2c"
      />

      <path d="M12 3v6" data-oid="de0d687" />
    </svg>
  )
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      data-oid="bavvode"
    >
      <circle cx="11" cy="11" r="8" data-oid="bfzra6g" />
      <path d="m21 21-4.3-4.3" data-oid="yhx7ksv" />
    </svg>
  )
}
