-- Wrap auth.uid()/current_setting() in RLS policy predicates in (select ...) so
-- Postgres evaluates each once per statement (an InitPlan) instead of once per row --
-- the Supabase-documented RLS perf pattern. Covers USING and WITH CHECK. Predicate-
-- equivalent (row visibility unchanged). Generated by 'pgrls fix --rule PERF001'
-- (pgrls 0.44.0) and verified on Postgres 16 (PERF001 -> 0).

-- [PERF001] Wrap auth function call(s) in policy 'project_invitations_delete_policy' on public.project_invitations so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY project_invitations_delete_policy ON public.project_invitations
    USING ((SELECT auth.uid()) = inviter_id OR user_has_project_access(project_id, ARRAY[CAST('owner' AS text), CAST('admin' AS text)]) OR EXISTS (SELECT 1 FROM auth.users WHERE users.id = auth.uid() AND users.email = CAST(project_invitations.invitee_email AS text)));

-- [PERF001] Wrap auth function call(s) in policy 'project_invitations_insert_policy' on public.project_invitations so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY project_invitations_insert_policy ON public.project_invitations
    WITH CHECK ((SELECT auth.uid()) = inviter_id AND user_has_project_access(project_id, ARRAY[CAST('owner' AS text), CAST('admin' AS text)]));

-- [PERF001] Wrap auth function call(s) in policy 'user_canvases_delete_policy' on public.user_canvases so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY user_canvases_delete_policy ON public.user_canvases
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'user_canvases_insert_policy' on public.user_canvases so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY user_canvases_insert_policy ON public.user_canvases
    WITH CHECK ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'user_canvases_select_policy' on public.user_canvases so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY user_canvases_select_policy ON public.user_canvases
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'user_canvases_update_policy' on public.user_canvases so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY user_canvases_update_policy ON public.user_canvases
    USING ((SELECT auth.uid()) = user_id)
    WITH CHECK ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'user_projects_delete_policy' on public.user_projects so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY user_projects_delete_policy ON public.user_projects
    USING ((SELECT auth.uid()) = user_id OR user_has_project_access(project_id, ARRAY[CAST('owner' AS text)]));

-- [PERF001] Wrap auth function call(s) in policy 'user_projects_select_policy' on public.user_projects so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY user_projects_select_policy ON public.user_projects
    USING ((SELECT auth.uid()) = user_id OR user_has_project_access(project_id, ARRAY[CAST('owner' AS text), CAST('admin' AS text)]));

-- [PERF001] Wrap auth function call(s) in policy 'user_settings_delete_policy' on public.user_settings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY user_settings_delete_policy ON public.user_settings
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'user_settings_insert_policy' on public.user_settings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY user_settings_insert_policy ON public.user_settings
    WITH CHECK ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'user_settings_select_policy' on public.user_settings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY user_settings_select_policy ON public.user_settings
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'user_settings_update_policy' on public.user_settings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY user_settings_update_policy ON public.user_settings
    USING ((SELECT auth.uid()) = user_id)
    WITH CHECK ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'users_delete_policy' on public.users so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY users_delete_policy ON public.users
    USING ((SELECT auth.uid()) = id);

-- [PERF001] Wrap auth function call(s) in policy 'users_insert_policy' on public.users so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY users_insert_policy ON public.users
    WITH CHECK ((SELECT auth.uid()) = id);

-- [PERF001] Wrap auth function call(s) in policy 'users_select_policy' on public.users so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY users_select_policy ON public.users
    USING ((SELECT auth.uid()) = id);

-- [PERF001] Wrap auth function call(s) in policy 'users_update_policy' on public.users so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY users_update_policy ON public.users
    USING ((SELECT auth.uid()) = id)
    WITH CHECK ((SELECT auth.uid()) = id);
