project_id = "studio"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public"]
max_rows = 100

[auth]
site_url = "https://onlook.dev"
additional_redirect_urls = ["onlook://auth"]
jwt_expiry = 36000

[db]
port = 54322

[studio]
port = 54323

[auth.external.github]
enabled = true
client_id = "env(GITHUB_CLIENT_ID)"
secret = "env(GITHUB_SECRET)"

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_SECRET)"

[analytics]
enabled = true
port = 54327
vector_port = 54328
backend = "postgres"