name: Run Unit Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v1
        with:
            bun-version: latest
      
      - name: Install dependencies
        run: bun install --frozen
      
      - name: Run tests
        run: bun test --timeout 30000 --coverage
